# Latent Dirichlet Allocation

* Prima di iniziare con la descrizione del progetto, ho esposto una sintesi di alcuni richiami teorici per contestualizzare l'oggetto di questo studio.

  I contenuti che seguono sono stati realizzati mettendo insieme [questa fonte](https://thesis.unipd.it/retrieve/8e03daa1-bdf5-4739-934a-d31420a6ffcb/Analisi%20ed%20applicazione%20di%20un%20algoritmo%20di%20Topic%20Modeling.pdf), appunti presi a lezione e le mie conoscenze pregresse in ambito probabilistico.



Il LDA (Latent Dirichlet Allocation) è un modello **generativo**, cioè un modello che descrive e **semplifica** il **processo di creazione di un documento testuale** all'interno di un corpus , assumendo che esso avvenga secondo una serie di passaggi probabilistici.
Nello specifico, il LDA adotta un **approccio bayesiano** : costruisce un processo stocastico che si presume abbia generato i  vari testi osservati nel corpus a partire da specifiche **ipotesi a priori**.
Il termine "**latente**" si riferisce a quelle variabili nascoste che intervengono nel processo di generazione del testo e che non sono direttamente osservabili. Nel contesto del LDA, tali variabili latenti corrispondono ai **topic**, intesi come distribuzioni di probabilità sull'insieme delle parole utilizzate nei vari documenti.

## Approccio bayesiano
### Regola di Bayes
 $$ \mathbb{P}(\theta \mid X )=\frac{\mathbb{P}(X \mid\theta)P(\theta)}{\mathbb{P}(X)} $$
 dove:
 * $ \mathbb{P}(\theta \mid X )$ è la Posterior distribution e rappresenta la probabilità a posteriori (dopo aver preso in considerazione i dati osservati) di $\theta$
 * $\mathbb{P}(\theta)$ è la prior distribution e definisce le ipotesi iniziali sul parametro $\theta$
 * $\mathbb{P}(X \mid \theta)$ è la cosidetta verosimiglianza e rappresenta la probabilità di
 osservare i dati assumendo il parametro $\theta$
 * $\mathbb{P}(X)$ è la probabilità di X che si può esprimere, condizionando su tutti i possibili valori che può assumere $\theta$, con la seguente formula:
 $$\mathbb{P}(X)=\int \mathbb{P}(X \mid \theta)\mathbb{P}(\theta) d\theta $$

 Quest' ultimo integrale, è spesso difficile da computare a causa dell'elevata dimensionalità dello spazio dei parametri. Per ovviare a questo problema, si utilizzano tecniche di stima che permettono, con buona approssimazione, di ottenere ugualmente un' espressione per la posterior distribution

## Descrizione del processo generativo
Descriviamo di seguito come avviene il processo generativo nel modello LDA, scegliendo un numero fissato T di topic, un numero D di documenti nel corpus, e un numero N di parole del vocabolario
1. Per ogni topic $t$ $\in \{1 \dots \text{T}\}$:
+ (a) A partire da una distr. di Dirichlet simmetrica, si estrae il parametro di una distr. multinomiale del topic $t$ sulle le parole del vocabolario, $\phi_z \sim  \text{Dir}(\beta)$
2. Per ogni documento $d$ $\in \{1 \dots D \}$
+ (a) A partitre da una distr. di Dirichlet simmetrica si estrae il parametro di una distr. multinomiale del documento $d$ sui topic, $\theta_d \sim \text{Dir}(\alpha)$
+ (b) Per ogni parola $w$ $\in \{ 1 \dots N_d\}$
   * (i) Viene estratto un topic dalla distr. del documento $d$ sui topic, $z_{dn} \sim \text{Multinomial} (\theta_d)$
   * (ii) Viene estratta una parola dalla distr. dei topic sulle parole, $w_{dn} \sim \text{Multinomial}(\phi_z)$
   ### Osservazione
   Nel caso del modello LDA, la prior distribution è dunque la distribuzione di Dirichlet che viene usata per estarre i parametri delle distribuzioni multinomiali:      
     * $\theta_d=(\theta_{d,1} \dots \theta_{d,T} )$ è la distr. dei documenti sui topic,e ogni entrata $i$ rappresenta la prob. del topic $i$ per il documento $d$ per cui $\sum_{i=1}^T \theta_{d,i}=1$
     * $\phi_z=(\phi_{z,1} \dots \phi_{z,N} )$ è la dist. dei topic sulle parole, e ogni entrata $j$ rappresenta la prob. della $j$-esia parola per il topic $t$ per cui $\sum_{j=1}^N \phi_{z,j}=1$

     ### Probabilità congiunta
     Riportiamo di seguito l' espressione per la probabilità congiunta del modello LDA, valida sotto le ipotesi di **cambiabilità dei documenti** e **scambiabilità delle parole**

  $$p(\textbf{z}, \textbf{w}, \theta_{1:D}, \phi_{1:T} \mid \alpha, \beta)= \prod_{t=1}^T p(\phi_t \mid \beta) \prod_{d=1}^D p(\theta_d \mid \alpha) \prod _{n=1}^{N_d}p(z_{dn}\mid \theta_d)p(w_{dn} \mid z_{dn}, \phi_{1:T})$$
  dove :   
  * $z_{dn}$ rappresenta l'assegnazione di un certo topic all' $n$-esima parola del documento d
  * $\textbf{z}$ è l'assegnazione di topic per tutte le parole
  * $\textbf{w}$ è l'insieme di tutte le parole che compaiono nel corpus di documenti

# Topic Modelling
La classe degli algoritmi di topic modelling, è quella classe di algoritmi che si occupa di ricavare informazioni da un insieme molto vasto di documenti, fornendo misure quantitative che possono essere utilizzate per identificare il contenuto dei testi, ossia definire quali sono gli argomenti trattati (topic).
 Il topic modelling, è una tecnica non supervisionata.Questo significa che non effettua l'apprendimento a partire da etichette preassegnate a ciascun documento della collezione, bensì ricava le distribuzioni di probabilità sulle parole del vocabolario associate a ciascuno dei topic. Attraverso l'analisi delle parole più probabili, sta a noi risalire a quale sia l'argomento trattato.

## Topic modelling tramite LDA
L'obiettivo centrale del modello LDA è rappresentato dall' inversione del processo generativo, al fine di determinare le variabili latenti date le variabili osservate (sequenza delle parole nei vari testi).
Le variabili latenti da determinare sono:
* $z_{dn} →$ assegnazione dei topic a ciascuna parola nei dcoumenti. Per ogni parola di un documento, vogliamo determinare a quale topic è assegnata
* $\theta_{1:D} →$ la distribuzione sui topic associata ad ogni documento $1 \dots D$
* $\phi_{1:T} →$ la distribuzione sulle parole associata ad ogni topic $1 \dots T$.

Il problema inferenziale che deve essere risolto, consiste nel calcolo della distr. a posteriori :
$$p(\textbf{z}, \theta_{1:D}, \phi_{1:T} \mid \textbf{w}, \alpha, \beta) = \frac{p(\textbf{z}, \theta_{1:D}, \phi_{1:T} , \textbf{w}\mid \alpha, \beta)}{p(\textbf{w} \mid \alpha,\beta)} $$
con la formula che è l'applicazione della formula di Bayes su più eventi:
$$\mathbb{P}(A \mid B \cap C)=\frac{ \mathbb{P}(A \cap B \cap C)} {\mathbb{P}(B \cap C)}=\frac{\mathbb{P}(A \cap B \mid C) \mathbb{P}(C)}{\mathbb{P}(B \cap C)}=\frac{\mathbb{P}(A \cap B \mid C )}{\mathbb{P}(B \mid C)} $$
Questa distribuzione, tuttavia, non è trattabile analiticamnete, essendo il denominatore ottenibile solo mediante integrazione da effettuare su uno spazio parametrico di elevata dimensionalità.
Quindi l'inferenza esatta è intrattabile, ma si può utilizzare l'inferenza approssimata utilizzando ad esempio il metodo del **Gibbs Sampling**. L'obiettivo consiste dunque nell'approssimare la distribuzione a posteriori ed ottenere una stima dei parametri tramite ottimizzazione.

# Gibbs Sampling
Il Gibbs Sampling, fa parte della classe di algoritmi del framework Markov Chain Montecarlo (MCMC) e viene usato per il **Topic Modelling**  nel contesto del LDA.
## Cenni su catene di Markov e metodo Montecarlo
### Catene di Markov
Una catena di Markov, è un processo stocastico costituito da una sequenza di variabili aleatorie $(X_n)_n$ che assumono valori in un certo spazio degli stati e che evolve nel tempo in accordo alla **proprietà di Markov** ovvero:
per ogni istante di tempo $n$, e per ogni possibile scelta di una sequenza di stati $x_0,x_1,\dots x_n$ che soddisfa $\mathbb{P}(X_0=x_0,\dots X_n=x_n)>0$ vale che $\mathbb{P}(X_{n+1}=x_{n+1} \mid X_n=x_n,\dots X_0=x_0)=\mathbb{P}(X_{n+1}=x_{n+1} \mid X_n=x_n)=P(x_n,x_{n+1})$.
 In altre parole, il processo, all’istante $n$, sceglie la sua posizione
 successiva tenedo conto solamente della sua posizione attuale $X_n$,
 dimenticando tutte le mosse effettuate in passato.
 Le catene di maggiore interesse, sono quelle che ammettono una distribuzione di probabilità stazionaria, ossia una distr. $\pi$ che soddisfa $\pi P=\pi $, vale a dire $\forall x$ $\pi(x)=\sum_y \pi(y)P(y,x)$.  Possiamo interpretare la definizione nella maniera seguente:
 se la distribuzione attuale è $\pi$, effettuando una transizione della
 catena, rimarremo distribuiti nello stesso modo.
 Queste distribuzioni assumono un ruolo centrale nello studio
 delle catene di Markov, poiché, sotto opportune condizioni, la
 misura stazionaria coincide con la distribuzione asintotica della
 catena.
 ### Metodo Montecarlo e relazione con la statistica Bayesiana
 Gli algoritmi MCMC, sfruttano le proprietà delle catene di Markov con l'obiettivo di simulare il campionamento da una certa distribuzione di probabilità target $\pi$ o analogamente computare $\mathbb{E}_{\pi}(f)$, il valore atteso di una funzione sotto la distribuzione $\pi$. Infatti, l'idea su cui si basano tali algoritmi, consiste nel costruire una catena di Markov che converga a $\pi$ (quindi che abbia $\pi$ come distr. stazionaria). La ragione principale alla base dell'implementazione di questo tipo  di tecniche, risiede nel fatto che le distribuzioni target assumono spesso espressioni  complicate, che dipendono da costanti di normalizzazione molto difficili da computare.
 Gli algoritmi MCMC trovano una naturale applicazione nel contesto dell' inferenza bayesiana. In questo tipo di paradigma infatti, come abbiamo visto, l'interesse è volto ad ottenere la densità **a posteriori** del vettore di parametri $\theta$.

# Utlizzo del Gibbs Sampling in LDA
L'obiettivo del Gibbs sampling applicato al modello LDA, è quello di costruire una catena di Markov che abbia la posterior distribution $p(\textbf{z}, \theta_{1:D}, \phi_{1:T} \mid \textbf{w}, \alpha, \beta)$ come distr. stazionaria, in modo tale che il comportamento della catena dopo un grande numero di passi approssimi bene la distr. stazionaria (in virtu del Teorema Ergodico).
Ogni stato della catena è rappresentato dalle variabili $z_{dn}$ che rappresentano le assegnazioni dei topi per ciascuna parola. Le transizioni tra gli stati successivi, invece, avvegono tramite il campionamento sequenziale delle assegnazioni $z_{dn}$ da una distr. condizionale $$ P(z_{dn}=k \mid z_{-dn}, w_{dn}, d)$$
dove :
* $z_{dn}$ corrisponde al topic campionato *k* assegnato alla parola $w_{dn}$
* $z_{-dn}$ rappresenta le  assegnazioni del topic in questione a tutte le altre parole.
Le variabili campionate vengono dunque modificate sequenzialmente fino a quando non viene raggiunta la distr. stazionaria della catena. Dopo aver stimato la distr. a posteriori di  $z_{dn}$, questa  viene sfruttata per dedurre le distr. $\phi_{1:T}$ e $\theta_{1:D}$.
La distr. condizionale del Gibbs Sampling è definita come:
$$ P(z_{dn}=k \mid z_{-dn}, w_{dn}, d) \propto \frac{C_{w_i,k}^1+\beta}{\sum_w C_{w,k}^1+ N\beta} \frac{C_{d,k}^2+\alpha}{\sum_t C_{d,t}^2 +T\alpha}$$
dove:
* $C^1$ è è la matrice il cui elemento $w_i,k$ rappresenta il conteggio di quante volte la parola $w_i$ è stata assegnata al topic $k$
* $C^2$ è è la matrice il cui elemento $d,k$ rappresenta il numero di volte che l'argomento $k$ è stato assegnato ad una qualsiasi parola del documento $d$
* $\sum_t C_{d,t}^2$ è il conteggio totale di assegnazioni di topic alle parole nel documento $d$
* $\sum_w C_{w,k}^1$ è il conteggio totale di parole assegnate al topic $k$.

Quindi per semplificare possiamo dire che questa espressione tiene conto di :
* Quanta "presenza di topic $k$" c'è nel documento d
* Quanto la parola $w$ partecipa al topic $k$

# Esecuzione dell' algoritmo
Per ogni documento $\{1 \dots D \}$ del corpus ripeti :

1. Si assegna a ciascuna parola $w_{dn}$ del documento un topic casuale $\{1 \dots T \}$
2. Per ciascuna parola $w_{dn}$ si iterano i seguenti passaggi:
    * Viene tolta l' assegnazione corrente della parola $w_{dn}$ all' argomento $k$.  Conseguentemente gli elementi $C_{w_i,k}^1$ e $C_{d,k}^2$ vengono decrementati di uno.
    * Un nuovo argomento viene campionato dalla distr. condizionale del Gibbs Sampling  ed assegnato alla parola $w_{dn}$: le matrici vengono aggiornate di conseguenza

Dunque, ad ogni iterazione,  si passa attraverso ciascun termine del corpus e si aggiorna l'assegnazione dei topic utilizzando una distr. condizionale basata sulle assegnazioni attuali per tutte le altre parole ($z_{-dn}$).

Al termine di un passaggio completo su tutte le parrole, si ottiene un campione di Gibbs che rappresenta lo stato corrente delle assegnazioni $z_{dn}$ per tutto il corpus di documenti. Questo processo viene ripetuto molte volte: durante la fase iniziale, detta **burn-in**, i campioni vengono scartati perchè non rappresentano accuratamente la distr. a posteriori, poi i campioni successivi, che iniziano a convergere verso la distr. target, vengono salvati a intervalli regolari per ridurre le correlazioni tra campioni consecutivi.
### Stima di $\theta_{1:D}$ e $\phi_{1:T}$
Per valutare il contenuto tematico dei documenti si richiedono le stime di $\theta_{1:D}$ e $\phi_{1:T}$. Queste grandezze possono essere facilmente ottenute a partire dai rapporti definiti in precedenza:

* $$\theta_{d,k}=\frac{C_{d,k}^2+\alpha}{\sum_t C_{d,t}^2+T\alpha} $$

* $$\phi_{k,wi}=\frac{C_{k,w_i}^1+\beta}{\sum_w C_{k,w}^1+N\beta} $$

# Descrizione del lavoro
In questo progetto, mi occuperò di implementare l'algoritmo di topic modelling utilizzando il modello LDA, a partire da un dataset contenente recensioni pubblicate sul portale Tripadvisor da utenti italiani.

[link al dataset scaricabile da Kaggle](https://www.kaggle.com/datasets/alessandrolobello/italian-tripadvisor)

Il lavoro verrà commentato passo passo e verranno iserite le considerazioni operative maturate durante lo svolgimento.

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

Matplotlib is building the font cache; this may take a moment.

In [140]:
#import os
#current_folder=os.getcwd()
#print(current_folder)

In [11]:
#caricamento del dataset
df=pd.read_csv("archive/LLM_DF.csv")
df

,Unnamed: 0,comment,title,date,name,stars
0,0,Questo è stato un interessante e piena di sera...,Zona del canal grande,26 ottobre 2016,gfdmmad,5.0
1,1,Ottimo e ben organizzato. Nessuna coda all'ent...,Visita di piacere,26 aprile 2019,Diabolik-Eva-014,5.0
2,2,Ci siamo stati molto spesso con gli amici o da...,Da vedere a Milano,18 novembre 2018,O5262KGchrisd,5.0
3,3,Consiglio di visitare il Duomo di Milano ....e...,Il Duomo sempre affascinante,7 agosto 2019,Babellina,5.0
4,4,La vista del duomo all'uscita della metro ti t...,Eccezionale,9 dicembre 2019,Nik804,5.0
...,...,...,...,...,...,...
20053,20053,Un bel parco in mezzo ad una delle città più g...,È bellissimo!,3 ottobre 2015,Giuseppe O,5.0
20054,20054,"Abbiamo passeggiato, bellissimi i riflessi del...",Navigli,1 gennaio 2020,michy77454,5.0
20055,20055,Che dire? Non manca proprio nulla: da Beato An...,Uno dei musei più belli del mondo,18 ottobre 2017,Ninotrapani,5.0
20056,20056,Spettacolare Porta simbolo della città di Berl...,Spettacolare Porta simbolo della città di Berl...,23 settembre 2019,Vincenzo P,5.0
20057,20057,La darsena con le varie biforcazioni così come...,Fantastico angolo di Milano che assolutamente ...,18 novembre 2016,Denis d,4.0

* Possiamo osservare che il dataset contiene più di 20000 recensioni registarte sul sito Tripadvisor
* Per ogni recensione sono riportati:
   * Identificativo progressivo
   * Titolo
   * Testo della recensione
   * data
   * nickname del recensore
   * rating(da 1 a 5 stelle)

* Otteniamo alcune informazioni sul dataset:
Vediamo quante recensioni sono presenti per ogni classe di rating (da 1 a 5 stelle)

In [12]:
df.groupby("stars").count()

       Unnamed: 0  comment  title   date   name
stars
1.0           126      126    126    126    126
2.0           222      222    222    222    222
3.0           911      911    911    911    911
4.0          4306     4306   4306   4306   4306
5.0         14493    14493  14493  14493  14493

* Vediamo qualche info sulle date

In [13]:
print(df["date"].max())
print(df["date"].min())

 9 settembre 2021
 1 agosto 2012

In [14]:
df["date"].describe()

count                20058
unique                2990
top        15 gennaio 2019
freq                    50
Name: date, dtype: object

* Cominciamo ad importare le librerie per il processamento del testo

In [16]:
import nltk
#from nltk.tokenize import word_tokenize, RegexpTokenizer

In [18]:
#nltk.download('punkt_tab')
#print("Download effettuato correttamente")

* Prendiamo una parte di testo a titolo di esempio, concatenando 3 recensioni e separandole tra loro andando a capo

In [20]:
pezzetto=df["comment"].iloc[10:12].str.cat(sep="\n")
print(pezzetto)

Visitare Milano nel periodo di Natale e' molto suggestivo e le mille luminarie che impreziosiscono la citta'la rendono ancora pu' magica.Tra i tanti eventi cui e' possibile assistere in questo periodo, consiglio a tutti le fontane danzanti sui Navigli.Ogni sera dopo il 7 dicembre dalle 18.30 in poi sulla Darsena si assiste a uno spettacolo meraviglioso: fontane d' acqua illuminate che passano dal bianco all'azzurro ai toni piu' accessi del rosso e dell' arancio  danzando al ritmo di musiche natalazie.Nei dintorni,le tipiche bancherelle con chioschi food e drink che ti riscalderanno.Per chi lo desidera e' possibile ogni giorno dal 16 novembre al 30 dicembre 2019 fare una navigazione sui Navigli accompagnati da un pianista compositore con la partecipazione di artisti del coro della Scala.Botteghini x acquisti biglietti in loco.
Bellissimo in questa stagione , abbiamo girato in bici e a piedi. Preso la barchetta a remi nel laghetto, mangiato in uno dei tanti ristorantino sparsi e poi rilassati sul prato all’ombra di un albero...

* Convertiamo la colonna delle recensioni in formato stringa per ottenere il corpus, in cui ogni documento è una singola recensione utente.

In [21]:
corpus=df["comment"].astype(str)
print(corpus)

0        Questo è stato un interessante e piena di sera...
1        Ottimo e ben organizzato. Nessuna coda all'ent...
2        Ci siamo stati molto spesso con gli amici o da...
3        Consiglio di visitare il Duomo di Milano ....e...
4        La vista del duomo all'uscita della metro ti t...
                               ...
20053    Un bel parco in mezzo ad una delle città più g...
20054    Abbiamo passeggiato, bellissimi i riflessi del...
20055    Che dire? Non manca proprio nulla: da Beato An...
20056    Spettacolare Porta simbolo della città di Berl...
20057    La darsena con le varie biforcazioni così come...
Name: comment, Length: 20058, dtype: object

* Vediamo il sesto documento

In [22]:
print(corpus[5])

Vivo a Milano da una vita ma non avevo mai trovato il tempo di visitare questa chiesa nel cuore di Milano e a due passi dall'Università Cattolica.Finalmente sono riuscito nell'intento e la bellezza degli affreschi presenti al suo interno ha superato le mie aspettative!

* Insatlliamo le librerie per il processamento del testo e per l'implementazione degli algoritmi di topic modelling

In [23]:
!pip install gensim pyLDAvis spacy scikit-learn

Collecting gensim
  Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl.metadata (8.6 kB)
Collecting pyLDAvis
  Downloading pyLDAvis-3.4.1-py3-none-any.whl.metadata (4.2 kB)
Collecting spacy
  Downloading spacy-3.8.11-cp313-cp313-win_amd64.whl.metadata (28 kB)
Requirement already satisfied: scikit-learn in c:\users\tmart\anaconda3\lib\site-packages (1.6.1)
Requirement already satisfied: numpy>=1.18.5 in c:\users\tmart\anaconda3\lib\site-packages (from gensim) (2.1.3)
Requirement already satisfied: scipy>=1.7.0 in c:\users\tmart\anaconda3\lib\site-packages (from gensim) (1.15.3)
Collecting smart_open>=1.8.1 (from gensim)
  Downloading smart_open-7.5.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: pandas>=2.0.0 in c:\users\tmart\anaconda3\lib\site-packages (from pyLDAvis) (2.2.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\tmart\anaconda3\lib\site-packages (from pyLDAvis) (1.4.2)
Requirement already satisfied: jinja2 in c:\users\tmart\anaconda3\lib\site-packages (from pyLDAvis) (3.1.6)
Requirement already satisfied: numexpr in c:\users\tmart\anaconda3\lib\site-packages (from pyLDAvis) (2.10.1)
Collecting funcy (from pyLDAvis)
  Downloading funcy-2.0-py2.py3-none-any.whl.metadata (5.9 kB)
Requirement already satisfied: setuptools in c:\users\tmart\anaconda3\lib\site-packages (from pyLDAvis) (72.1.0)
Collecting spacy-legacy<3.1.0,>=3.0.11 (from spacy)
  Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl.metadata (2.8 kB)
Collecting spacy-loggers<2.0.0,>=1.0.0 (from spacy)
  Downloading spacy_loggers-1.0.5-py3-none-any.whl.metadata (23 kB)
Collecting murmurhash<1.1.0,>=0.28.0 (from spacy)
  Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl.metadata (2.3 kB)
Collecting cymem<2.1.0,>=2.0.2 (from spacy)
  Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl.metadata (9.9 kB)
Collecting preshed<3.1.0,>=3.0.2 (from spacy)
  Downloading preshed-3.0.12-cp313-cp313-win_amd64.whl.metadata (2.6 kB)
Collecting thinc<8.4.0,>=8.3.4 (from spacy)
  Downloading thinc-8.3.10-cp313-cp313-win_amd64.whl.metadata (15 kB)
Collecting wasabi<1.2.0,>=0.9.1 (from spacy)
  Downloading wasabi-1.1.3-py3-none-any.whl.metadata (28 kB)
Collecting srsly<3.0.0,>=2.4.3 (from spacy)
  Downloading srsly-2.5.2-cp313-cp313-win_amd64.whl.metadata (20 kB)
Collecting catalogue<2.1.0,>=2.0.6 (from spacy)
  Downloading catalogue-2.0.10-py3-none-any.whl.metadata (14 kB)
Collecting weasel<0.5.0,>=0.4.2 (from spacy)
  Downloading weasel-0.4.3-py3-none-any.whl.metadata (4.6 kB)
Collecting typer-slim<1.0.0,>=0.3.0 (from spacy)
  Downloading typer_slim-0.20.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\tmart\anaconda3\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\tmart\anaconda3\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\tmart\anaconda3\lib\site-packages (from spacy) (2.10.3)
Requirement already satisfied: packaging>=20.0 in c:\users\tmart\anaconda3\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\tmart\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.6.0)
Requirement already satisfied: pydantic-core==2.27.1 in c:\users\tmart\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.27.1)
Requirement already satisfied: typing-extensions>=4.12.2 in c:\users\tmart\anaconda3\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.12.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\tmart\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\tmart\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\tmart\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\tmart\anaconda3\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2025.11.12)
Collecting blis<1.4.0,>=1.3.0 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading blis-1.3.3-cp313-cp313-win_amd64.whl.metadata (7.7 kB)
Collecting confection<1.0.0,>=0.0.1 (from thinc<8.4.0,>=8.3.4->spacy)
  Downloading confection-0.1.5-py3-none-any.whl.metadata (19 kB)
Requirement already satisfied: colorama in c:\users\tmart\anaconda3\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.0.0 in c:\users\tmart\anaconda3\lib\site-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.1.8)
Collecting cloudpathlib<1.0.0,>=0.7.0 (from weasel<0.5.0,>=0.4.2->spacy)
  Downloading cloudpathlib-0.23.0-py3-none-any.whl.metadata (16 kB)
Requirement already satisfied: wrapt in c:\users\tmart\anaconda3\lib\site-packages (from smart_open>=1.8.1->gensim) (1.17.0)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\tmart\anaconda3\lib\site-packages (from scikit-learn) (3.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\tmart\anaconda3\lib\site-packages (from pandas>=2.0.0->pyLDAvis) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\tmart\anaconda3\lib\site-packages (from pandas>=2.0.0->pyLDAvis) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\tmart\anaconda3\lib\site-packages (from pandas>=2.0.0->pyLDAvis) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\tmart\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->pyLDAvis) (1.17.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\tmart\anaconda3\lib\site-packages (from jinja2->pyLDAvis) (3.0.2)
Downloading gensim-4.4.0-cp313-cp313-win_amd64.whl (24.4 MB)
   ---------------------------------------- 0.0/24.4 MB ? eta -:--:--
   --- ------------------------------------ 2.1/24.4 MB 10.2 MB/s eta 0:00:03
   ----- ---------------------------------- 3.1/24.4 MB 8.9 MB/s eta 0:00:03
   -------- ------------------------------- 5.2/24.4 MB 8.5 MB/s eta 0:00:03
   ------------ --------------------------- 7.3/24.4 MB 8.9 MB/s eta 0:00:02
   -------------- ------------------------- 8.7/24.4 MB 8.2 MB/s eta 0:00:02
   ----------------- ---------------------- 10.5/24.4 MB 8.8 MB/s eta 0:00:02
   -------------------- ------------------- 12.6/24.4 MB 8.7 MB/s eta 0:00:02
   ---------------------- ----------------- 13.9/24.4 MB 8.3 MB/s eta 0:00:02
   ------------------------- -------------- 15.7/24.4 MB 8.7 MB/s eta 0:00:01
   ----------------------------- ---------- 17.8/24.4 MB 8.7 MB/s eta 0:00:01
   -------------------------------- ------- 19.9/24.4 MB 8.7 MB/s eta 0:00:01
   ---------------------------------- ----- 21.0/24.4 MB 8.7 MB/s eta 0:00:01
   ------------------------------------- -- 23.1/24.4 MB 8.7 MB/s eta 0:00:01
   ---------------------------------------- 24.4/24.4 MB 8.4 MB/s eta 0:00:00
Downloading pyLDAvis-3.4.1-py3-none-any.whl (2.6 MB)
   ---------------------------------------- 0.0/2.6 MB ? eta -:--:--
   ---------------------------------------- 2.6/2.6 MB 26.4 MB/s eta 0:00:00
Downloading spacy-3.8.11-cp313-cp313-win_amd64.whl (14.2 MB)
   ---------------------------------------- 0.0/14.2 MB ? eta -:--:--
   ---------------------- ----------------- 8.1/14.2 MB 38.9 MB/s eta 0:00:01
   ---------------------------------------- 14.2/14.2 MB 33.7 MB/s eta 0:00:00
Downloading catalogue-2.0.10-py3-none-any.whl (17 kB)
Downloading cymem-2.0.13-cp313-cp313-win_amd64.whl (40 kB)
Downloading murmurhash-1.0.15-cp313-cp313-win_amd64.whl (25 kB)
Downloading preshed-3.0.12-cp313-cp313-win_amd64.whl (117 kB)
Downloading spacy_legacy-3.0.12-py2.py3-none-any.whl (29 kB)
Downloading spacy_loggers-1.0.5-py3-none-any.whl (22 kB)
Downloading srsly-2.5.2-cp313-cp313-win_amd64.whl (653 kB)
   ---------------------------------------- 0.0/653.1 kB ? eta -:--:--
   --------------------------------------- 653.1/653.1 kB 17.8 MB/s eta 0:00:00
Downloading thinc-8.3.10-cp313-cp313-win_amd64.whl (1.7 MB)
   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 30.2 MB/s eta 0:00:00
Downloading blis-1.3.3-cp313-cp313-win_amd64.whl (6.2 MB)
   ---------------------------------------- 0.0/6.2 MB ? eta -:--:--
   ---------------------------------------- 6.2/6.2 MB 35.0 MB/s eta 0:00:00
Downloading confection-0.1.5-py3-none-any.whl (35 kB)
Downloading typer_slim-0.20.0-py3-none-any.whl (47 kB)
Downloading wasabi-1.1.3-py3-none-any.whl (27 kB)
Downloading weasel-0.4.3-py3-none-any.whl (50 kB)
Downloading cloudpathlib-0.23.0-py3-none-any.whl (62 kB)
Downloading smart_open-7.5.0-py3-none-any.whl (63 kB)
Downloading funcy-2.0-py2.py3-none-any.whl (30 kB)
Installing collected packages: funcy, wasabi, spacy-loggers, spacy-legacy, smart_open, murmurhash, cymem, cloudpathlib, catalogue, blis, typer-slim, srsly, preshed, gensim, pyLDAvis, confection, weasel, thinc, spacy

   -- -------------------------------------  1/19 [wasabi]
   ------ ---------------------------------  3/19 [spacy-legacy]
   -------- -------------------------------  4/19 [smart_open]
   ------------ ---------------------------  6/19 [cymem]
   -------------- -------------------------  7/19 [cloudpathlib]
   ------------------ ---------------------  9/19 [blis]
   --------------------- ------------------ 10/19 [typer-slim]
   ----------------------- ---------------- 11/19 [srsly]
   ----------------------- ---------------- 11/19 [srsly]
   ----------------------- ---------------- 11/19 [srsly]
   ----------------------- ---------------- 11/19 [srsly]
   ----------------------- ---------------- 11/19 [srsly]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   --------------------------- ------------ 13/19 [gensim]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   ----------------------------- ---------- 14/19 [pyLDAvis]
   --------------------------------- ------ 16/19 [weasel]
   --------------------------------- ------ 16/19 [weasel]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ----------------------------------- ---- 17/19 [thinc]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ------------------------------------- -- 18/19 [spacy]
   ---------------------------------------- 19/19 [spacy]

Successfully installed blis-1.3.3 catalogue-2.0.10 cloudpathlib-0.23.0 confection-0.1.5 cymem-2.0.13 funcy-2.0 gensim-4.4.0 murmurhash-1.0.15 preshed-3.0.12 pyLDAvis-3.4.1 smart_open-7.5.0 spacy-3.8.11 spacy-legacy-3.0.12 spacy-loggers-1.0.5 srsly-2.5.2 thinc-8.3.10 typer-slim-0.20.0 wasabi-1.1.3 weasel-0.4.3

In [24]:
import string
import spacy
import gensim
from gensim import corpora
from gensim.models import CoherenceModel
import pyLDAvis.gensim_models as gensimvis
import pyLDAvis
from nltk.corpus import stopwords

nltk.download('wordnet')
nltk.download('stopwords')


from nltk.corpus import stopwords
italian_stopwords = stopwords.words('italian')

[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\tmart\AppData\Roaming\nltk_data...
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\tmart\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

In [25]:
print(italian_stopwords)

['ad', 'al', 'allo', 'ai', 'agli', 'all', 'agl', 'alla', 'alle', 'con', 'col', 'coi', 'da', 'dal', 'dallo', 'dai', 'dagli', 'dall', 'dagl', 'dalla', 'dalle', 'di', 'del', 'dello', 'dei', 'degli', 'dell', 'degl', 'della', 'delle', 'in', 'nel', 'nello', 'nei', 'negli', 'nell', 'negl', 'nella', 'nelle', 'su', 'sul', 'sullo', 'sui', 'sugli', 'sull', 'sugl', 'sulla', 'sulle', 'per', 'tra', 'contro', 'io', 'tu', 'lui', 'lei', 'noi', 'voi', 'loro', 'mio', 'mia', 'miei', 'mie', 'tuo', 'tua', 'tuoi', 'tue', 'suo', 'sua', 'suoi', 'sue', 'nostro', 'nostra', 'nostri', 'nostre', 'vostro', 'vostra', 'vostri', 'vostre', 'mi', 'ti', 'ci', 'vi', 'lo', 'la', 'li', 'le', 'gli', 'ne', 'il', 'un', 'uno', 'una', 'ma', 'ed', 'se', 'perché', 'anche', 'come', 'dov', 'dove', 'che', 'chi', 'cui', 'non', 'più', 'quale', 'quanto', 'quanti', 'quanta', 'quante', 'quello', 'quelli', 'quella', 'quelle', 'questo', 'questi', 'questa', 'queste', 'si', 'tutto', 'tutti', 'a', 'c', 'e', 'i', 'l', 'o', 'ho', 'hai', 'ha', 'abbiamo', 'avete', 'hanno', 'abbia', 'abbiate', 'abbiano', 'avrò', 'avrai', 'avrà', 'avremo', 'avrete', 'avranno', 'avrei', 'avresti', 'avrebbe', 'avremmo', 'avreste', 'avrebbero', 'avevo', 'avevi', 'aveva', 'avevamo', 'avevate', 'avevano', 'ebbi', 'avesti', 'ebbe', 'avemmo', 'aveste', 'ebbero', 'avessi', 'avesse', 'avessimo', 'avessero', 'avendo', 'avuto', 'avuta', 'avuti', 'avute', 'sono', 'sei', 'è', 'siamo', 'siete', 'sia', 'siate', 'siano', 'sarò', 'sarai', 'sarà', 'saremo', 'sarete', 'saranno', 'sarei', 'saresti', 'sarebbe', 'saremmo', 'sareste', 'sarebbero', 'ero', 'eri', 'era', 'eravamo', 'eravate', 'erano', 'fui', 'fosti', 'fu', 'fummo', 'foste', 'furono', 'fossi', 'fosse', 'fossimo', 'fossero', 'essendo', 'faccio', 'fai', 'facciamo', 'fanno', 'faccia', 'facciate', 'facciano', 'farò', 'farai', 'farà', 'faremo', 'farete', 'faranno', 'farei', 'faresti', 'farebbe', 'faremmo', 'fareste', 'farebbero', 'facevo', 'facevi', 'faceva', 'facevamo', 'facevate', 'facevano', 'feci', 'facesti', 'fece', 'facemmo', 'faceste', 'fecero', 'facessi', 'facesse', 'facessimo', 'facessero', 'facendo', 'sto', 'stai', 'sta', 'stiamo', 'stanno', 'stia', 'stiate', 'stiano', 'starò', 'starai', 'starà', 'staremo', 'starete', 'staranno', 'starei', 'staresti', 'starebbe', 'staremmo', 'stareste', 'starebbero', 'stavo', 'stavi', 'stava', 'stavamo', 'stavate', 'stavano', 'stetti', 'stesti', 'stette', 'stemmo', 'steste', 'stettero', 'stessi', 'stesse', 'stessimo', 'stessero', 'stando']

In [26]:
import warnings
warnings.filterwarnings("ignore")

In [27]:
from sklearn.feature_extraction.text import CountVectorizer

* Vediamo una prima esecuzione dell' algoritmo:

volutamente, la fase di processamento del testo, è stata ridotta al minimo indispensabile (ovvero considerando la sola rimozione delle stopwords)

In [28]:
bow=CountVectorizer(max_features=10000,stop_words=italian_stopwords,lowercase=True)
X=bow.fit_transform(corpus)
print(X.shape)

(20058, 10000)

In [29]:
features = bow.get_feature_names_out()
print("vediamo tutte le features: ", features,'\n')
print("vediamone una decina di features: \n", features[1000:1010], '\n')  # stampiamone una decina
print("vediamo la feature n.245: ", features[245], '\n')  # stampiamone una decina

vediamo tutte le features:  ['00' '000' '01' ... 'ztl' 'zurbaran' 'zza']

vediamone una decina di features:
 ['babbo' 'babila' 'bacino' 'bacio' 'badge' 'bagagli' 'bagaglio' 'bagnato'
 'bagni' 'bagno']

vediamo la feature n.245:  addosso

In [30]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

* la cella che segue impiega circa 7 minuti e mezzo per essere eseguita

In [48]:
from sklearn.decomposition import LatentDirichletAllocation as LDA

# fissiamo a-priori il numero di topics (10) ed il numero di iterazioni
n_topics = 10

lda = LDA(n_components=n_topics, max_iter=100,random_state=100, verbose=False)
new_lda = lda.fit_transform(X)

In [49]:
print('Document Topic Matrix: \n', np.array(lda), '\n')
print(new_lda, '\n')
print(len(new_lda), '\n')

print("ecco la distribuzione di probabilità sui topic del primo articolo: \n", np.array(new_lda[0]),'\n')
print("la somma delle probabiltà è: ", np.sum(new_lda[0]),'\n')

Document Topic Matrix:
 LatentDirichletAllocation(max_iter=100, random_state=100, verbose=False)

[[0.00208402 0.00208378 0.00208359 ... 0.0020837  0.00208372 0.08586779]
 [0.00833397 0.00833437 0.00833438 ... 0.00833358 0.00833611 0.92499264]
 [0.00285742 0.00285767 0.00285735 ... 0.00285763 0.06480793 0.00285727]
 ...
 [0.18662397 0.00476241 0.00476228 ... 0.00476236 0.00476278 0.77527635]
 [0.01       0.01000101 0.13757968 ... 0.78241598 0.01000097 0.0100002 ]
 [0.00357213 0.00357219 0.00357204 ... 0.00357218 0.00357269 0.00357194]]

20058

ecco la distribuzione di probabilità sui topic del primo articolo:
 [0.00208402 0.00208378 0.00208359 0.0020834  0.00208362 0.00208375
 0.89746265 0.0020837  0.00208372 0.08586779]

la somma delle probabiltà è:  1.0

In [50]:
print(new_lda.shape)

(20058, 10)

lda_components è invece la matrice topic x words , in cui per  ogni riga viene espressa la frequenza (ratio) di tutte le parole presenti nel vocabolario prestabilito all'interno del topic indicizzato dal numero di riga. quindi il numero di righe coincide con  numero di topic settato come **iperparametro**

lda.components_[i][j] è la **ratio** della parola j nel topic i, ovvero il numero di volte che la j-esima parola viene attribuita al topic i

In [51]:
print(len(lda.components_))    # numero dei topics: 10
print(len(lda.components_[0])) # numero delle word del vocabolario: 10000
print("Topic Word Matrix: \n")
j=0
for i  in lda.components_:
    print("topic ", j+1, i, '\n')
    j+=1

10
10000
Topic Word Matrix:

topic  1 [ 0.1000175  11.68171953  0.10000892 ...  0.10002826  0.10003298
  0.10002628]

topic  2 [0.10000783 0.1000251  4.099978   ... 0.10003348 0.1        0.1       ]

topic  3 [0.10000953 0.10001462 0.1        ... 0.1        0.1        0.10001935]

topic  4 [0.10000627 0.10001608 0.1        ... 0.10001268 0.10003079 0.1       ]

topic  5 [0.10002402 5.51804648 0.1        ... 0.1        0.1        0.10002002]

topic  6 [0.10001188 0.10003877 0.10000697 ... 1.09994987 4.09981879 0.1       ]

topic  7 [22.05772755  0.1000005   0.1        ...  2.09997571  0.10000331
  0.10009368]

topic  8 [0.10000344 0.10010728 0.1        ... 0.1        0.1        8.09982752]

topic  9 [0.10001537 0.10001842 0.1        ... 0.1        0.1        0.10000782]

topic  10 [2.14142177e+02 1.00013211e-01 1.00006114e-01 ... 1.00000000e-01
 1.00114132e-01 1.00005318e-01]

In [52]:
print(lda.components_.shape)

(10, 10000)

* Calcoliamo ora, a titolo di esempio, il "peso"(inteso come misura della frequenza) di una delle feature all'interno del primo topic

In [53]:
feature_100 = bow.get_feature_names_out()[1000]
print(feature_100)

babbo

In [54]:
freq_sul_topic_0=lda.components_[0]
#Questo è il vettore con i pesi di tutte le parole nel ptimo topic
print(freq_sul_topic_0)

[ 0.1000175  11.68171953  0.10000892 ...  0.10002826  0.10003298
  0.10002628]

In [55]:
print(f"il peso della parola {features[1000]} nel primo topic è {freq_sul_topic_0[1000]}")

il peso della parola babbo nel primo topic è 0.10000189808009924

In [56]:
for i in range(len(lda.components_)):
  print(f"il peso di  {features[1000]} nel topic {i+1} è {lda.components_[i][1000]}")

il peso di  babbo nel topic 1 è 0.10000189808009924
il peso di  babbo nel topic 2 è 0.100003455357653
il peso di  babbo nel topic 3 è 0.10000091611346046
il peso di  babbo nel topic 4 è 0.10000000033896392
il peso di  babbo nel topic 5 è 0.10000091380335839
il peso di  babbo nel topic 6 è 7.0999414676620525
il peso di  babbo nel topic 7 è 0.10002946843520345
il peso di  babbo nel topic 8 è 0.10000000016051364
il peso di  babbo nel topic 9 è 0.10000171948944424
il peso di  babbo nel topic 10 è 0.10002016052346165

In [57]:
print(f"il peso totale di {features[1000]} in tutti i topics è {lda.components_.sum(axis=0)[1000]}")#somma per colonne

il peso totale di babbo in tutti i topics è 7.999999999964211

* Per ottenere $\mathbb{P}(\text{parola}\mid \text{topic}(k))$, bisogna normalizzare rispetto somma dei pesi assegnati a tutte le parole all'interno dello stesso topic $k$:

$$\mathbb{P}(w_j \mid z_{w_j}=k)=\frac{\text{ldacomponents}_{[k,j]}}{\sum_i \text{ldacomponents}_{[k,i]}}$$

In [58]:
print(f"Quindi la prob. che {features[1000]} sia campionata dal topic 1 è {lda.components_[0][100]/lda.components_[0].sum()}")

Quindi la prob. che babbo sia campionata dal topic 1 è 2.2578376351684304e-06

In [59]:
topic_word_prob = lda.components_ / lda.components_.sum(axis=1)[:, None]


print('la probabilità di ciascuna delle 10000 parole del dizionario di essere campionate  dal topic 1: ')
topic_proba_0 = topic_word_prob[0]
print(topic_proba_0, '\n') # è la probabilità di ciascuna delle 10000 parole del dizionario
print("La somma per riga è \n")                                # di essere campionate dal topic 1
print(np.sum(topic_proba_0),'\n')

la probabilità di ciascuna delle 10000 parole del dizionario di essere campionate  dal topic 1:
[2.25812594e-06 2.63741771e-04 2.25793205e-06 ... 2.25836879e-06
 2.25847524e-06 2.25832402e-06]

La somma per riga è

1.0000000000000002

In [60]:
print(topic_word_prob.shape)

(10, 10000)

sommando ogni  colonna di topic_word_prob otteniamo un vettore di dimensione 10000 in cui ogni entrata è un valore (non è una probabilità) che ci dà un indicazione di quanto ogni parola è globalmente distribuita tra tutti i topic

In [61]:
topic_word_proba_sum = topic_word_prob.sum(axis=0)
print(topic_word_proba_sum)
print(len(topic_word_proba_sum))

[4.35552522e-03 3.66535509e-04 5.75765569e-05 ... 1.04884821e-04
 2.26040347e-04 2.15175794e-04]
10000

* Adesso estraiamo le parole più popolari di ogni topic e valutiamo il risultato ottenuto

In [62]:
n_words = 10
for index, topic in enumerate(lda.components_):
    # stampiamo gli indici delle prime 10 parole più popolari, usiamo argsort() per ordinarle in senso crescente,
    # quindi prenderemo gli ultimi 10 indici, denotando l'intervallo come [-10:]
    print("\nTOPIC %d - indici delle %d parole più popolari" % (index+1, n_words))
    print([i for i in topic.argsort()[-n_words:]])

    # utilizziamo il dizionario per trovare le parole in base agli indici
    print("\nTOPIC %d - %d parole più popolari (ordinate crescenti)" % (index+1, n_words))
    print([features[i] for i in topic.argsort()[-n_words:]])

    print('______________________________________________________________________________')

TOPIC 1 - indici delle 10 parole più popolari
[np.int64(3711), np.int64(6398), np.int64(8805), np.int64(9850), np.int64(3342), np.int64(6683), np.int64(2224), np.int64(5493), np.int64(2716), np.int64(8532)]

TOPIC 1 - 10 parole più popolari (ordinate crescenti)
['forse', 'peccato', 'stato', 'visto', 'essere', 'poco', 'cosa', 'molto', 'dire', 'solo']
______________________________________________________________________________

TOPIC 2 - indici delle 10 parole più popolari
[np.int64(5493), np.int64(3473), np.int64(1718), np.int64(1142), np.int64(9708), np.int64(9974), np.int64(5734), np.int64(1550), np.int64(6265), np.int64(6248)]

TOPIC 2 - 10 parole più popolari (ordinate crescenti)
['molto', 'fare', 'città', 'bici', 'verde', 'york', 'new', 'central', 'park', 'parco']
______________________________________________________________________________

TOPIC 3 - indici delle 10 parole più popolari
[np.int64(9811), np.int64(9641), np.int64(1718), np.int64(4608), np.int64(9916), np.int64(9817), np.int64(6595), np.int64(8239), np.int64(5399), np.int64(3019)]

TOPIC 3 - 10 parole più popolari (ordinate crescenti)
['visita', 'vedere', 'città', 'interno', 'volta', 'visitare', 'piazza', 'sempre', 'milano', 'duomo']
______________________________________________________________________________

TOPIC 4 - indici delle 10 parole più popolari
[np.int64(2429), np.int64(2274), np.int64(8239), np.int64(5889), np.int64(5931), np.int64(5084), np.int64(6284), np.int64(8272), np.int64(7176), np.int64(1089)]

TOPIC 4 - 10 parole più popolari (ordinate crescenti)
['davanti', 'così', 'sempre', 'occhi', 'ogni', 'mai', 'parole', 'senza', 'quando', 'bellezza']
______________________________________________________________________________

TOPIC 5 - indici delle 10 parole più popolari
[np.int64(5499), np.int64(6287), np.int64(4994), np.int64(8435), np.int64(9910), np.int64(9811), np.int64(1423), np.int64(315), np.int64(5399), np.int64(1619)]

TOPIC 5 - 10 parole più popolari (ordinate crescenti)
['monache', 'parte', 'luini', 'sistina', 'volontari', 'visita', 'cappella', 'affreschi', 'milano', 'chiesa']
______________________________________________________________________________

TOPIC 6 - indici delle 10 parole più popolari
[np.int64(5823), np.int64(5493), np.int64(5525), np.int64(1535), np.int64(8239), np.int64(8247), np.int64(5260), np.int64(1165), np.int64(5019), np.int64(6724)]

TOPIC 6 - 10 parole più popolari (ordinate crescenti)
['notte', 'molto', 'monumento', 'cemento', 'sempre', 'senso', 'memoriale', 'blocchi', 'luogo', 'porta']
______________________________________________________________________________

TOPIC 7 - indici delle 10 parole più popolari
[np.int64(1032), np.int64(6346), np.int64(6796), np.int64(7754), np.int64(8285), np.int64(5493), np.int64(9993), np.int64(4940), np.int64(5670), np.int64(5399)]

TOPIC 7 - 10 parole più popolari (ordinate crescenti)
['bar', 'passeggiata', 'posto', 'ristoranti', 'sera', 'molto', 'zona', 'locali', 'navigli', 'milano']
______________________________________________________________________________

TOPIC 8 - indici delle 10 parole più popolari
[np.int64(3726), np.int64(5592), np.int64(5019), np.int64(6287), np.int64(5493), np.int64(1718), np.int64(9641), np.int64(8834), np.int64(1118), np.int64(5599)]

TOPIC 8 - 10 parole più popolari (ordinate crescenti)
['foto', 'murales', 'luogo', 'parte', 'molto', 'città', 'vedere', 'storia', 'berlino', 'muro']
______________________________________________________________________________

TOPIC 9 - indici delle 10 parole più popolari
[np.int64(922), np.int64(4089), np.int64(6270), np.int64(4085), np.int64(8834), np.int64(4585), np.int64(4141), np.int64(2368), np.int64(5493), np.int64(9811)]

TOPIC 9 - 10 parole più popolari (ordinate crescenti)
['audioguida', 'gratuito', 'parlamento', 'gratuita', 'storia', 'interessante', 'guida', 'cupola', 'molto', 'visita']
______________________________________________________________________________

TOPIC 10 - indici delle 10 parole più popolari
[np.int64(3597), np.int64(2058), np.int64(5042), np.int64(5493), np.int64(4480), np.int64(6014), np.int64(757), np.int64(9811), np.int64(5975), np.int64(5603)]

TOPIC 10 - 10 parole più popolari (ordinate crescenti)
['fila', 'consiglio', 'madrid', 'molto', 'ingresso', 'ore', 'arte', 'visita', 'opere', 'museo']
______________________________________________________________________________

* Definiamo una funzione per classificare nuove rewiew all'interno di questi topic che abbiamo ricavato

In [63]:


def classify(text, return_proba=False):
    x = bow.transform([text]) # utilizziamo il metodo transform del bow sfruttando il fitting eseguito precedentemente, ricordiamo che l'input deve essere un array
    y_proba = lda.transform(x)[0] # siccome restituisce un array di array, prendiamo solo la prima componente con le propabilità di appartenza a ciascuno dei 25 topics
    y = y_proba.argmax()

    if(return_proba):
        y_proba_p = np.sort(y_proba)
        print("y_proba in senso crescente: \n", y_proba_p, "\n")

        topics_orderedp = np.argsort(y_proba)
        print("topics_ordered in senso crescente: \n", topics_orderedp, "\n")

        topics_ordered = np.argsort(-y_proba)
        print("topics_ordered  in senso decrescente: \n", topics_ordered, "\n")

        y_proba = -np.sort(-y_proba)
        print("y_proba in senso decrescente: \n", y_proba, "\n")

        y_dict = dict(["TOPIC: "+str(topic+1), proba] for topic, proba in zip(topics_ordered, y_proba))
        return y, y_dict

    return y

In [64]:
my_rewiew = "cappella spettacolare, gli  affreschi delle vergini  mi hanno fatto sentire in contatto spirituale con Dio"
y, y_proba = classify(my_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y+1))
print("\n")
for topic in y_proba:
    print("%s = %.4f" % (topic, y_proba[topic]))

y_proba in senso crescente:
 [0.01111199 0.01111232 0.01111242 0.01111248 0.01111407 0.0111142
 0.01111543 0.01111596 0.16739102 0.74370012]

topics_ordered in senso crescente:
 [6 7 3 9 8 1 0 2 5 4]

topics_ordered  in senso decrescente:
 [4 5 2 0 1 8 9 3 7 6]

y_proba in senso decrescente:
 [0.74370012 0.16739102 0.01111596 0.01111543 0.0111142  0.01111407
 0.01111248 0.01111242 0.01111232 0.01111199]

Topic di appartenenza: 5


TOPIC: 5 = 0.7437
TOPIC: 6 = 0.1674
TOPIC: 3 = 0.0111
TOPIC: 1 = 0.0111
TOPIC: 2 = 0.0111
TOPIC: 9 = 0.0111
TOPIC: 10 = 0.0111
TOPIC: 4 = 0.0111
TOPIC: 8 = 0.0111
TOPIC: 7 = 0.0111

In [65]:
my_second_rewiew="La zona dei giardini completamente immersa nel verde è quella che più mi ha affascinato"
y1, y_proba1 = classify(my_second_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y1+1))
print("\n")
for topic in y_proba1:
    print("%s = %.4f" % (topic, y_proba1[topic]))

y_proba in senso crescente:
 [0.01428571 0.01428571 0.01428601 0.01428717 0.01428866 0.01428983
 0.01429611 0.17106471 0.25724113 0.47167495]

topics_ordered in senso crescente:
 [0 2 9 5 7 8 4 6 3 1]

topics_ordered  in senso decrescente:
 [1 3 6 4 8 7 5 9 2 0]

y_proba in senso decrescente:
 [0.47167495 0.25724113 0.17106471 0.01429611 0.01428983 0.01428866
 0.01428717 0.01428601 0.01428571 0.01428571]

Topic di appartenenza: 2


TOPIC: 2 = 0.4717
TOPIC: 4 = 0.2572
TOPIC: 7 = 0.1711
TOPIC: 5 = 0.0143
TOPIC: 9 = 0.0143
TOPIC: 8 = 0.0143
TOPIC: 6 = 0.0143
TOPIC: 10 = 0.0143
TOPIC: 3 = 0.0143
TOPIC: 1 = 0.0143

In [66]:
my_third_rewiew="La gita è stata memorabile, i mezzi di trasporto molto efficienti"
y2, y2_proba = classify(my_third_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y2+1))
print("\n")
for topic in y2_proba:
    print("%s = %.4f" % (topic, y2_proba[topic]))

y_proba in senso crescente:
 [0.01250073 0.01250125 0.01250128 0.01250167 0.01250206 0.01250209
 0.01250358 0.01250508 0.16112666 0.73885559]

topics_ordered in senso crescente:
 [5 4 3 2 7 1 0 8 9 6]

topics_ordered  in senso decrescente:
 [6 9 8 0 1 7 2 3 4 5]

y_proba in senso decrescente:
 [0.73885559 0.16112666 0.01250508 0.01250358 0.01250209 0.01250206
 0.01250167 0.01250128 0.01250125 0.01250073]

Topic di appartenenza: 7


TOPIC: 7 = 0.7389
TOPIC: 10 = 0.1611
TOPIC: 9 = 0.0125
TOPIC: 1 = 0.0125
TOPIC: 2 = 0.0125
TOPIC: 8 = 0.0125
TOPIC: 3 = 0.0125
TOPIC: 4 = 0.0125
TOPIC: 5 = 0.0125
TOPIC: 6 = 0.0125

In [67]:
my_fourth_rewiew="In treno era possibile portare con se la bicicletta, in modo da visitare il paese alto senza faticare troppo"
y3, y3_proba = classify(my_fourth_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y3+1))
print("\n")
for topic in y3_proba:
    print("%s = %.4f" % (topic, y3_proba[topic]))

y_proba in senso crescente:
 [0.00909199 0.00909209 0.00909295 0.00909302 0.0090933  0.00909426
 0.16495362 0.17488875 0.29401535 0.31158466]

topics_ordered in senso crescente:
 [5 4 3 9 6 8 7 2 0 1]

topics_ordered  in senso decrescente:
 [1 0 2 7 8 6 9 3 4 5]

y_proba in senso decrescente:
 [0.31158466 0.29401535 0.17488875 0.16495362 0.00909426 0.0090933
 0.00909302 0.00909295 0.00909209 0.00909199]

Topic di appartenenza: 2


TOPIC: 2 = 0.3116
TOPIC: 1 = 0.2940
TOPIC: 3 = 0.1749
TOPIC: 8 = 0.1650
TOPIC: 9 = 0.0091
TOPIC: 7 = 0.0091
TOPIC: 10 = 0.0091
TOPIC: 4 = 0.0091
TOPIC: 5 = 0.0091
TOPIC: 6 = 0.0091

In [68]:
my_fifth_rewiew="Stoccolma è magia pura"
y4, y4_proba = classify(my_fifth_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y4+1))
print("\n")
for topic in y4_proba:
    print("%s = %.4f" % (topic, y4_proba[topic]))

y_proba in senso crescente:
 [0.03333333 0.03333333 0.03333333 0.03333333 0.03333415 0.03333532
 0.03333654 0.0333388  0.03335186 0.69997   ]

topics_ordered in senso crescente:
 [9 7 2 8 6 0 4 1 3 5]

topics_ordered  in senso decrescente:
 [5 3 1 4 0 6 8 2 7 9]

y_proba in senso decrescente:
 [0.69997    0.03335186 0.0333388  0.03333654 0.03333532 0.03333415
 0.03333333 0.03333333 0.03333333 0.03333333]

Topic di appartenenza: 6


TOPIC: 6 = 0.7000
TOPIC: 4 = 0.0334
TOPIC: 2 = 0.0333
TOPIC: 5 = 0.0333
TOPIC: 1 = 0.0333
TOPIC: 7 = 0.0333
TOPIC: 9 = 0.0333
TOPIC: 3 = 0.0333
TOPIC: 8 = 0.0333
TOPIC: 10 = 0.0333

In [69]:
my_sixth_rewiew="parchi, chiese, musei, arte, natura, bici-friendly, esperienze e visite guidate: questa città offre qualsiasi cosa tu voglia; è completa in tutto"
y5, y5_proba = classify(my_sixth_rewiew, return_proba=True)

print("Topic di appartenenza: %d" % (y5+1))
print("\n")
for topic in y5_proba:
    print("%s = %.4f" % (topic, y5_proba[topic]))

y_proba in senso crescente:
 [0.00625039 0.00625093 0.00625144 0.00625213 0.00625249 0.00625253
 0.00625413 0.11194829 0.29808035 0.54620731]

topics_ordered in senso crescente:
 [5 6 3 0 7 2 8 4 9 1]

topics_ordered  in senso decrescente:
 [1 9 4 8 2 7 0 3 6 5]

y_proba in senso decrescente:
 [0.54620731 0.29808035 0.11194829 0.00625413 0.00625253 0.00625249
 0.00625213 0.00625144 0.00625093 0.00625039]

Topic di appartenenza: 2


TOPIC: 2 = 0.5462
TOPIC: 10 = 0.2981
TOPIC: 5 = 0.1119
TOPIC: 9 = 0.0063
TOPIC: 3 = 0.0063
TOPIC: 8 = 0.0063
TOPIC: 1 = 0.0063
TOPIC: 4 = 0.0063
TOPIC: 7 = 0.0063
TOPIC: 6 = 0.0063

# Considerazioni

Possiamo vedere come le parole più rappresentative di ciascuno dei 10 topic, solo in alcuni casi diano informazioni utili per ricostruire l'argomento: ad esempio il topic 2 con le parole : "parco","central","park","verde" raggruppa tutte qulle recensioni in cui sono state fornite descrizioni riguardanti la visita dei parchi e delle zone verdi (in particolare Central Park) . D' altro canto, in altri casi come nel topic 1, la maggior parte delle parole più popolari selezionate sono aggettivi o avverbi ("molto","forse","poco","solo"), e perciò non permettono di ricostruire bene l'argomento trattato nelle recensioni.
Quindi le problematiche principali sono state:
 * la scelta di selezionare 10 come numero di topic da scovare (iperparametro) : alcuni topic ricostruiti sembrano essere ridondanti visto che selezionano le stesse parole chiave
 * il processamento ridotto alla sola esclusione delle stop words, ha permesso  di tener conto di tutte quelle parole (in particolare aggettivi e avverbi) utilizzate per enfatizzare emozioni e giudizi, che sono presenti nella maggior parte delle rewiew (ad esempio "molto").

 Per quanto riguarda la classificazione di nuove recensioni, attraverso la funzione appositamente definita, l'algoritmo si comporta abbatanza bene  quando la rewiew fornita in input contiene specifiche parole chiave selezionate unicamente nel topic di riferimento (ad esempio my_second_rewiew con un focus su "giardini" e "zone verdi"), mentre fa più fatica quando la recensione non contiene le parole chiave estratte o ne mischia diverse selezionate in topic differenti.

* Sulla base degli accorgimenti appena detti, modifichiamo il codice introducendo un processamento del testo più selettivo e diminuendo a 8 il numero di topic da ricavare

* Usiamo la libreria spacy per un processamento del testo più accurato. In particolare implementiamo una routine di processeamneto pre-addestrata su un grande dataset contenente migliaia di notizie in lingua italiana

In [70]:
!python -m spacy download it_core_news_sm

Collecting it-core-news-sm==3.8.0
  Downloading https://github.com/explosion/spacy-models/releases/download/it_core_news_sm-3.8.0/it_core_news_sm-3.8.0-py3-none-any.whl (13.0 MB)
     ---------------------------------------- 0.0/13.0 MB ? eta -:--:--
     -------------- ------------------------- 4.7/13.0 MB 25.5 MB/s eta 0:00:01
     ------------------------------------- - 12.6/13.0 MB 31.8 MB/s eta 0:00:01
     --------------------------------------- 13.0/13.0 MB 27.9 MB/s eta 0:00:00
Installing collected packages: it-core-news-sm
Successfully installed it-core-news-sm-3.8.0
[+] Download and installation successful
You can now load the package via spacy.load('it_core_news_sm')

In [71]:
nlp = spacy.load("it_core_news_sm")
print("Modello caricato correttamente ")

Modello caricato correttamente

In [72]:
!pip install wordfreq

Collecting wordfreq
  Downloading wordfreq-3.1.1-py3-none-any.whl.metadata (27 kB)
Collecting ftfy>=6.1 (from wordfreq)
  Downloading ftfy-6.3.1-py3-none-any.whl.metadata (7.3 kB)
Collecting langcodes>=3.0 (from wordfreq)
  Downloading langcodes-3.5.1-py3-none-any.whl.metadata (30 kB)
Collecting locate<2.0.0,>=1.1.1 (from wordfreq)
  Downloading locate-1.1.1-py3-none-any.whl.metadata (3.9 kB)
Collecting msgpack<2.0.0,>=1.0.7 (from wordfreq)
  Downloading msgpack-1.1.2-cp313-cp313-win_amd64.whl.metadata (8.4 kB)
Requirement already satisfied: regex>=2023.10.3 in c:\users\tmart\anaconda3\lib\site-packages (from wordfreq) (2024.11.6)
Requirement already satisfied: wcwidth in c:\users\tmart\anaconda3\lib\site-packages (from ftfy>=6.1->wordfreq) (0.2.5)
Downloading wordfreq-3.1.1-py3-none-any.whl (56.8 MB)
   ---------------------------------------- 0.0/56.8 MB ? eta -:--:--
   --- ------------------------------------ 5.2/56.8 MB 29.0 MB/s eta 0:00:02
   ----- ---------------------------------- 7.3/56.8 MB 17.6 MB/s eta 0:00:03
   ----- ---------------------------------- 8.4/56.8 MB 15.6 MB/s eta 0:00:04
   ------- -------------------------------- 10.5/56.8 MB 13.4 MB/s eta 0:00:04
   -------- ------------------------------- 12.6/56.8 MB 12.5 MB/s eta 0:00:04
   ---------- ----------------------------- 14.7/56.8 MB 11.8 MB/s eta 0:00:04
   ----------- ---------------------------- 16.3/56.8 MB 11.1 MB/s eta 0:00:04
   ------------ --------------------------- 17.8/56.8 MB 11.3 MB/s eta 0:00:04
   ------------- -------------------------- 19.4/56.8 MB 10.5 MB/s eta 0:00:04
   -------------- ------------------------- 20.4/56.8 MB 9.8 MB/s eta 0:00:04
   ---------------- ----------------------- 23.1/56.8 MB 10.3 MB/s eta 0:00:04
   ---------------- ----------------------- 24.1/56.8 MB 10.0 MB/s eta 0:00:04
   ------------------ --------------------- 26.2/56.8 MB 9.9 MB/s eta 0:00:04
   ------------------- -------------------- 28.3/56.8 MB 9.8 MB/s eta 0:00:03
   --------------------- ------------------ 30.4/56.8 MB 9.8 MB/s eta 0:00:03
   ---------------------- ----------------- 31.5/56.8 MB 9.7 MB/s eta 0:00:03
   ----------------------- ---------------- 33.6/56.8 MB 9.6 MB/s eta 0:00:03
   ----------------------- ---------------- 33.8/56.8 MB 9.1 MB/s eta 0:00:03
   ------------------------- -------------- 35.7/56.8 MB 9.2 MB/s eta 0:00:03
   -------------------------- ------------- 37.7/56.8 MB 9.2 MB/s eta 0:00:03
   ---------------------------- ----------- 39.8/56.8 MB 9.2 MB/s eta 0:00:02
   ----------------------------- ---------- 41.4/56.8 MB 9.1 MB/s eta 0:00:02
   ------------------------------ --------- 43.0/56.8 MB 9.2 MB/s eta 0:00:02
   ------------------------------- -------- 44.3/56.8 MB 8.9 MB/s eta 0:00:02
   -------------------------------- ------- 46.1/56.8 MB 9.0 MB/s eta 0:00:02
   --------------------------------- ------ 48.0/56.8 MB 8.9 MB/s eta 0:00:01
   ---------------------------------- ----- 49.3/56.8 MB 9.0 MB/s eta 0:00:01
   ------------------------------------ --- 51.4/56.8 MB 8.9 MB/s eta 0:00:01
   ------------------------------------- -- 53.2/56.8 MB 8.9 MB/s eta 0:00:01
   ------------------------------------- -- 53.5/56.8 MB 8.9 MB/s eta 0:00:01
   -------------------------------------- - 54.5/56.8 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  56.6/56.8 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------  56.6/56.8 MB 8.6 MB/s eta 0:00:01
   ---------------------------------------- 56.8/56.8 MB 8.2 MB/s eta 0:00:00
Downloading locate-1.1.1-py3-none-any.whl (5.4 kB)
Downloading msgpack-1.1.2-cp313-cp313-win_amd64.whl (72 kB)
Downloading ftfy-6.3.1-py3-none-any.whl (44 kB)
Downloading langcodes-3.5.1-py3-none-any.whl (183 kB)
Installing collected packages: msgpack, locate, langcodes, ftfy, wordfreq

  Attempting uninstall: msgpack

    Found existing installation: msgpack 1.0.3

    Uninstalling msgpack-1.0.3:

      Successfully uninstalled msgpack-1.0.3

   ---------------- ----------------------- 2/5 [langcodes]
   -------------------------------- ------- 4/5 [wordfreq]
   -------------------------------- ------- 4/5 [wordfreq]
   ---------------------------------------- 5/5 [wordfreq]

Successfully installed ftfy-6.3.1 langcodes-3.5.1 locate-1.1.1 msgpack-1.1.2 wordfreq-3.1.1

In [73]:
from wordfreq import zipf_frequency
#La funzione zipf_frequency serve a stimare la frequenza di una parola in lingua naturale in base a quanto “comune” o “rara” è quella parola.

In [74]:
def clean_text(text):
    doc = nlp(text.lower())
    token_puliti = []

    for tok in doc:
        if tok.is_stop: #rimozione stopwords
            continue
        if tok.pos_ in ["ADV", "ADJ"]:  # rimuove avverbi e aggettivi
            continue
        if tok.is_punct or tok.is_space or tok.like_num: #rimozione spazi punteggiatura e numeri(anche scritti a lettere)
            continue
        if not tok.is_alpha: #manenimento token che contengono solo lettere
            continue
        if not zipf_frequency(tok.lemma_, 'it') > 2: #rimozione parole troppo rare
            continue

        token_puliti.append(tok.lemma_) # lemmatizzazione

    return " ".join(token_puliti)

* Apllichiamo questa funzione di pre-processamneto del testo al nostro corpus (circa 5 minuti per l'esecuzione)

In [75]:
corpus_cleam=[clean_text(document)for document in corpus]

* Oltre ad utilizzare il testo ripulito  tramite la routine pre-addestrata di Spacy, con max_df=1000 rimuoviamo i vocaboli che compaiono in più di 1000 documenti, e con min_df=2 rimuoviamo quelle parole troppo rare all'interno del corpus (quelle che compaiono una sola volta - 1 di document frequency). Inoltre aggiungiamo alle stopwords una lista che inseriamo a mano contenente tutte quelle parole utilizzate per enfatizzare i giudizi.

In [76]:


parole_per_enfatizzare = [
    "molto", "troppo", "poco", "più", "meno", "abbastanza",
    "niente", "nulla", "tanto",  "molti", "poche",
    "stupendo", "bellissimo", "bruttissimo", "magnifico",
    "grazie", "prego", "perfetto", "orribile", "fantastico",
    "meglio", "peggio", "ottimo", "buono", "buona","magico","incredibile","incantevole","emozionante","sicuramente","certamente","peccato","dispiace","piacevole","negativa","postiva","tutto","bello","brutto","assolutamente","stupefacente","sensazionale","emozionante","quando","senza","mai","vale","pena","grande","solo","dopo","poi","mentre","durante","senza","sempre","ogni","vedere","entrare"
]

stopwords_finali = list(set(
    italian_stopwords
    + parole_per_enfatizzare

))

In [77]:
bow1=CountVectorizer(max_features=25000,max_df=1000,min_df=2,stop_words=stopwords_finali,lowercase=True)
X1=bow1.fit_transform(corpus_cleam)
print(X1.shape)

(20058, 6769)

* Dopo questi passaggi sono rimaste 6769 features

In [78]:
features_cl = bow1.get_feature_names_out()
print("vediamo tutte le features: ", features_cl,'\n')
print("vediamone una decina di features: \n", features_cl[1000:1010], '\n')  # stampiamone una decina
print("vediamo la feature n.245: ", features_cl[245], '\n')  # stampiamone una decina

vediamo tutte le features:  ['abbagliare' 'abbandonare' 'abbandonata' ... 'zoo' 'zoom' 'ztl']

vediamone una decina di features:
 ['capitello' 'capitolo' 'capo' 'capodanno' 'capogiro' 'capolavoro'
 'capolinea' 'capolino' 'capoluogo' 'cappa']

vediamo la feature n.245:  america

* Anche per questa cella c'è da attendere alcuni minuti (circa 6)

In [89]:
n_topics = 8

lda1 = LDA(n_components=n_topics, max_iter=150,random_state=31, verbose=False)
#random_state serve per la riproducibilità dei risultati
# con verbose=False disattivo le scritte a schermo relative alle varie esecuzioni
new_lda1 = lda1.fit_transform(X1)

In [90]:
print("Ecco la matrice document topic: \n")
print(new_lda1, '\n')

Ecco la matrice document topic:

[[0.00694866 0.71787843 0.00694612 ... 0.00694768 0.00694623 0.00696014]
 [0.01785998 0.01785798 0.87497435 ... 0.01787205 0.01785714 0.01785714]
 [0.00658794 0.79995822 0.00657907 ... 0.00658139 0.10032115 0.00658084]
 ...
 [0.00962026 0.00961743 0.93266309 ... 0.00961746 0.00961577 0.00962499]
 [0.01562767 0.01563009 0.01563015 ... 0.17380213 0.7323947  0.015641  ]
 [0.00962374 0.93265115 0.00961957 ... 0.00961586 0.00962991 0.00961582]]

In [91]:
print("Ecco ora la matrice topic word: \n")
j=0
for i in range(len(lda1.components_)):
   print(f"topic {j+1}: {lda1.components_[i]}")
   print("\n")
   j=j+1
print(f"Questa matrice matrice ha dimensioni {lda1.components_.shape}")

Ecco ora la matrice topic word:

topic 1: [1.25001930e-01 5.88929863e+00 1.25000018e-01 ... 3.68124838e+02
 2.12491148e+00 3.12417984e+00]


topic 2: [0.12500001 0.12538475 0.12782941 ... 0.12501834 0.12500001 0.12513043]


topic 3: [0.12501088 0.12505339 1.12323504 ... 0.12502675 0.12500002 0.12500002]


topic 4: [0.12503    0.12502832 0.12500005 ... 0.12501667 0.12500003 0.12505023]


topic 5: [11.12479216  3.32425005  0.12500003 ...  0.12500616  0.12500002
  0.12500001]


topic 6: [0.12502098 0.12527496 0.12515531 ... 0.12501139 0.12508838 0.12500002]


topic 7: [ 0.12504487 16.16058807  0.12500008 ...  0.1250377   0.12500004
  0.12552467]


topic 8: [0.12509916 0.12512183 1.12378007 ... 0.12504501 0.12500002 0.12511479]


Questa matrice matrice ha dimensioni (8, 6769)

In [92]:
print(f"La probabilità che la parola {features_cl[3456]} appartenga al topic {len(lda1.components_)} è {lda1.components_[7][3456]/lda1.components_[7].sum()}")

La probabilità che la parola mago appartenga al topic 8 è 5.4943936015419955e-06

In [93]:
max=8
for index, topic in enumerate(lda1.components_):
    # stampiamo gli indici delle prime 10 parole più popolari, usiamo argsort() per ordinarle in senso crescente,
    # quindi prenderemo gli ultimi 10 indici, denotando l'intervallo come [-10:]
    print("\nTOPIC %d - indici delle %d parole più popolari" % (index+1, max))
    print([i for i in topic.argsort()[-max:]])

    # utilizziamo il dizionario per trovare le parole in base agli indici
    print("\nTOPIC %d - %d parole più popolari (ordinate crescenti)" % (index+1, max))
    print([features_cl[i] for i in topic.argsort()[-max:]])

    print('______________________________________________________________________________')

TOPIC 1 - indici delle 8 parole più popolari
[np.int64(2775), np.int64(5422), np.int64(3239), np.int64(2421), np.int64(4446), np.int64(772), np.int64(2703), np.int64(2700)]

TOPIC 1 - 8 parole più popolari (ordinate crescenti)
['grattacielo', 'scoiattolo', 'laghetto', 'film', 'polmone', 'bicicletta', 'giro', 'girare']
______________________________________________________________________________

TOPIC 2 - indici delle 8 parole più popolari
[np.int64(964), np.int64(2631), np.int64(3831), np.int64(3832), np.int64(670), np.int64(5171), np.int64(5547), np.int64(3347)]

TOPIC 2 - 8 parole più popolari (ordinate crescenti)
['canale', 'gente', 'navigli', 'naviglio', 'bar', 'ristorante', 'sera', 'locale']
______________________________________________________________________________

TOPIC 3 - indici delle 8 parole più popolari
[np.int64(4745), np.int64(2812), np.int64(4507), np.int64(3437), np.int64(1271), np.int64(2417), np.int64(779), np.int64(3062)]

TOPIC 3 - 8 parole più popolari (ordinate crescenti)
['quadro', 'guida', 'prado', 'madrid', 'coda', 'fila', 'biglietto', 'ingresso']
______________________________________________________________________________

TOPIC 4 - indici delle 8 parole più popolari
[np.int64(721), np.int64(6657), np.int64(258), np.int64(2811), np.int64(5637), np.int64(5300), np.int64(6186), np.int64(4364)]

TOPIC 4 - 8 parole più popolari (ordinate crescenti)
['bellezza', 'vista', 'ammirare', 'guglia', 'simbolo', 'salire', 'terrazza', 'piazza']
______________________________________________________________________________

TOPIC 5 - indici delle 8 parole più popolari
[np.int64(2684), np.int64(3735), np.int64(1574), np.int64(6283), np.int64(3733), np.int64(3399), np.int64(5666), np.int64(6694)]

TOPIC 5 - 8 parole più popolari (ordinate crescenti)
['gioiello', 'monastero', 'coro', 'touring', 'monaca', 'luino', 'sistina', 'volontario']
______________________________________________________________________________

TOPIC 6 - indici delle 8 parole più popolari
[np.int64(5667), np.int64(2812), np.int64(4177), np.int64(3789), np.int64(2511), np.int64(3582), np.int64(4557), np.int64(1690)]

TOPIC 6 - 8 parole più popolari (ordinate crescenti)
['sito', 'guida', 'parlamento', 'murales', 'foto', 'memoriale', 'prenotare', 'cupola']
______________________________________________________________________________

TOPIC 7 - indici delle 8 parole più popolari
[np.int64(3681), np.int64(4364), np.int64(3753), np.int64(852), np.int64(4807), np.int64(445), np.int64(3642), np.int64(4465)]

TOPIC 7 - 8 parole più popolari (ordinate crescenti)
['minuto', 'piazza', 'monumento', 'brandeburgo', 'raggiungere', 'arrivare', 'metro', 'porta']
______________________________________________________________________________

TOPIC 8 - indici delle 8 parole più popolari
[np.int64(2045), np.int64(6119), np.int64(6671), np.int64(4279), np.int64(4181), np.int64(2136), np.int64(3257), np.int64(5065)]

TOPIC 8 - 8 parole più popolari (ordinate crescenti)
['dovere', 'tappa', 'vivere', 'pensare', 'parola', 'emozione', 'lasciare', 'rimanere']
______________________________________________________________________________

* Il risultato è decisamente più soddisfacente : ad eccezione del topic 8 che "rimane un pò vago" , le parole chiave ricavate, sembrano inquadrare un argomento specifico tra quelli trattati nelle varie recensioni.
- 3 Arte e Musei
- 2 Movida milanese nella zona dei Navigli
- 1 Attività nel verde urbano
- 5 Turismo religioso
- 4 Location panoramiche
- 7 Itinerari turistici
- 6 Visite guidate

* Adesso ripetiamo gli stessi passaggi per i titoli delle recensioni, analizzando il caso delle recensioni postive (da 3 stelle in su) e di quelle negative (massimo 2 stelle)

* Obiettivo:  Valutare se l'algorimo di topic extraction  a partire dal modello LDA è efficace per scopi di sentiment classification

In [94]:
title_str_positive=df[df["stars"]>=3]["title"].astype(str)
title_str_positive

0                                    Zona del canal grande
1                                        Visita di piacere
2                                       Da vedere a Milano
3                             Il Duomo sempre affascinante
4                                              Eccezionale
                               ...
20053                                        È bellissimo!
20054                                             Navigli
20055                    Uno dei musei più belli del mondo
20056    Spettacolare Porta simbolo della città di Berl...
20057    Fantastico angolo di Milano che assolutamente ...
Name: title, Length: 19710, dtype: object

In [95]:
title_str_negative=df[df["stars"]<3]["title"].astype(str)
title_str_negative

10          Giochi d'acqua natalizi e navigazione musicale
15                                       Non è il migliore
23                                                  Noioso
88                                          Caratteristico
113                                          Niente di che
                               ...
19506    Tristissima imitazione di un ambiente del passato
19656              bello e caratteristico....ma non sempre
19727                                            Delusione
19856                         Solo per anglofoni, peccato!
19861                                              Mah....
Name: title, Length: 348, dtype: object

*  in questo caso manteniamo aggettivi e avverbi che, come abbiamo detto, sono fondamentali per conferire enfasi ai giudizi

In [96]:
def clean_titles(text):
    doc = nlp(text.lower())
    token_puliti = []

    for tok in doc:
        if tok.is_stop: #rimozione stopwords
            continue
       # if tok.pos_ in ["ADV", "ADJ"]:  # in questo caso manteniamo aggettivi e avverbi che, come abbiamo detto, sono fondamentali per conferire enfasi ai giudizi
         #   continue
        if tok.is_punct or tok.is_space or tok.like_num: #rimozione spazi punteggiatura e numeri(anche scritti a lettere)
            continue
        if not tok.is_alpha: #manenimento token che contengono solo lettere
            continue
        if not zipf_frequency(tok.lemma_, 'it') > 2: #rimozione parole troppo rare
            continue

        token_puliti.append(tok.lemma_) # lemmatizzazione

    return " ".join(token_puliti)

In [97]:
title_pos_clean=[clean_titles(t) for t in title_str_positive]
title_neg_clean=[clean_titles(t) for t in title_str_negative]

In [113]:
bowtitlepos=CountVectorizer(max_features=5000,stop_words=italian_stopwords,max_df=0.8,min_df=2 ,lowercase=True)
Xtitlepos=bowtitlepos.fit_transform(title_pos_clean)
print(Xtitlepos.shape)

(19710, 1535)

In [114]:
title_feature_pos=bowtitlepos.get_feature_names_out()
print(f"Ecco tutte le feature: {title_feature_pos}")
print(f"Ecco una decina di feature: {title_feature_pos[1000:1010]}")
print(f"Ecco la feature numero 245: {title_feature_pos[245]}")

Ecco tutte le feature: ['abbraccio' 'abitare' 'abito' ... 'zona' 'zonzo' 'zoo']
Ecco una decina di feature: ['percorrere' 'percorso' 'perdere' 'pere' 'perfetto' 'perfezione'
 'periodo' 'perla' 'personale' 'personalmente']
Ecco la feature numero 245: colorare

In [115]:
number_of_topics=5 #diminuiamo a 5 l'iperparametro
lda_title_pos=LDA(n_components=number_of_topics,max_iter=200,random_state=56,verbose=False)
new_lda_title_pos=lda_title_pos.fit_transform(Xtitlepos)

In [116]:
print("Ecco la matrice document topic: \n")
print(new_lda_title_pos, '\n')

Ecco la matrice document topic:

[[0.0679074  0.06666754 0.39883557 0.06666762 0.39992187]
 [0.06666695 0.066667   0.4000427  0.06666702 0.39995633]
 [0.06666669 0.06666669 0.06666669 0.40000127 0.39999865]
 ...
 [0.73055623 0.06666673 0.06944357 0.06666673 0.06666674]
 [0.37413272 0.04000032 0.23987865 0.30598791 0.0400004 ]
 [0.19999592 0.03333344 0.20000685 0.36669707 0.19996671]]

In [117]:
print("Ecco ora la matrice topic word: \n")
j=0
for i in range (len(lda_title_pos.components_)):
   print(f"topic {j+1}: {lda_title_pos.components_[i]}")
   print("\n")
   j=j+1

Ecco ora la matrice topic word:

topic 1: [ 0.20003211  0.20001933  0.20001395 ... 36.38089256  0.20001731
  0.20001259]


topic 2: [0.20003634 0.20292302 0.20001578 ... 0.20091966 0.20001934 0.20001419]


topic 3: [ 0.20003785  0.20002322  0.20001644 ... 62.01483485  0.20002013
  0.20095858]


topic 4: [2.19984964 2.19633956 2.1999347  ... 0.20254722 0.20002103 0.20001577]


topic 5: [0.20004406 0.20069487 0.20001913 ... 0.20080571 3.1999222  7.19899887]

In [118]:
print(f"La probabilità che la parola {title_feature_pos[567]} appartenga al topic {len(lda_title_pos.components_)} è {lda_title_pos.components_[4][567]/ lda_title_pos.components_[4].sum()} ")

La probabilità che la parola grattacielo appartenga al topic 5 è 3.33124402771373e-05

In [119]:
max=8
for index, topic in enumerate(lda_title_pos.components_):
    # stampiamo gli indici delle prime 10 parole più popolari, usiamo argsort() per ordinarle in senso crescente,
    # quindi prenderemo gli ultimi 10 indici, denotando l'intervallo come [-10:]
    print("\nTOPIC %d - indici delle %d parole più popolari" % (index+1, max))
    print([i for i in topic.argsort()[-max:]])

    # utilizziamo il dizionario per trovare le parole in base agli indici
    print("\nTOPIC %d - %d parole più popolari (ordinate crescenti)" % (index+1, max))
    print([title_feature_pos[i] for i in topic.argsort()[-max:]])

    print('______________________________________________________________________________')

TOPIC 1 - indici delle 8 parole più popolari
[np.int64(138), np.int64(224), np.int64(979), np.int64(1326), np.int64(536), np.int64(461), np.int64(1353), np.int64(131)]

TOPIC 1 - 8 parole più popolari (ordinate crescenti)
['berlino', 'chiesa', 'passeggiata', 'spettacolare', 'gioiello', 'fantastico', 'storia', 'bello']
______________________________________________________________________________

TOPIC 2 - indici delle 8 parole più popolari
[np.int64(315), np.int64(902), np.int64(85), np.int64(1528), np.int64(876), np.int64(1038), np.int64(791), np.int64(1484)]

TOPIC 2 - 8 parole più popolari (ordinate crescenti)
['cuore', 'oasi', 'arte', 'york', 'new', 'polmone', 'meraviglioso', 'verde']
______________________________________________________________________________

TOPIC 3 - indici delle 8 parole più popolari
[np.int64(811), np.int64(846), np.int64(665), np.int64(603), np.int64(1503), np.int64(978), np.int64(1002), np.int64(1501)]

TOPIC 3 - 8 parole più popolari (ordinate crescenti)
['milanese', 'museo', 'interessante', 'immenso', 'visitare', 'passeggiare', 'perdere', 'visita']
______________________________________________________________________________

TOPIC 4 - indici delle 8 parole più popolari
[np.int64(98), np.int64(197), np.int64(1283), np.int64(612), np.int64(1288), np.int64(787), np.int64(389), np.int64(812)]

TOPIC 4 - 8 parole più popolari (ordinate crescenti)
['assolutamente', 'cappello', 'simbolo', 'imperdibile', 'sistina', 'meraviglia', 'duomo', 'milano']
______________________________________________________________________________

TOPIC 5 - indici delle 8 parole più popolari
[np.int64(194), np.int64(480), np.int64(1380), np.int64(1461), np.int64(214), np.int64(963), np.int64(966), np.int64(1474)]

TOPIC 5 - 8 parole più popolari (ordinate crescenti)
['capolavoro', 'film', 'suggestivo', 'unico', 'central', 'parco', 'park', 'vedere']
______________________________________________________________________________

* Passiamo alle recensioni negative

In [124]:
bowtitleneg=CountVectorizer(max_features=5000,stop_words=italian_stopwords,min_df=2,lowercase=True)
Xtitleneg=bowtitleneg.fit_transform(title_neg_clean)
print(Xtitleneg.shape)

(348, 84)

In [127]:
title_feature_neg=bowtitleneg.get_feature_names_out()
print(f"Ecco tutte le feature: {title_feature_neg}")
print(f"Ecco una decina di feature: {title_feature_neg[70:80]}")
print(f"Ecco la feature numero 74: {title_feature_neg[74]}")

Ecco tutte le feature: ['abbandono' 'accogliente' 'acqua' 'arte' 'aspettare' 'bah' 'bello'
 'berlino' 'biglietto' 'brutto' 'canale' 'caos' 'caratteristico'
 'chiudere' 'chiuso' 'confusione' 'cuore' 'cupola' 'degrado' 'deludente'
 'deludere' 'delusione' 'deluso' 'dispersivo' 'duomo' 'eccezionale'
 'entrare' 'esperienza' 'evitare' 'fare' 'gente' 'interessante' 'locale'
 'madrid' 'mah' 'memoriale' 'meraviglioso' 'migliore' 'milano' 'mortale'
 'movida' 'muro' 'museo' 'natalizio' 'navigli' 'noia' 'noioso' 'occasione'
 'opera' 'organizzazione' 'pagare' 'particolare' 'pensare' 'percorso'
 'personale' 'pessimo' 'piacere' 'poco' 'potere' 'prado' 'prenotazione'
 'ridicolo' 'rumore' 'serata' 'simbolo' 'sopravvalutare' 'sopravvalutato'
 'splendido' 'sporco' 'squallido' 'stare' 'storia' 'tanto' 'totale'
 'trascurare' 'turista' 'unico' 'valorizzare' 'vedere' 'vergogna'
 'viaggio' 'visita' 'visitare' 'zona']
Ecco una decina di feature: ['stare' 'storia' 'tanto' 'totale' 'trascurare' 'turista' 'unico'
 'valorizzare' 'vedere' 'vergogna']
Ecco la feature numero 74: trascurare

In [128]:
number_of_topics=3   #ho decrementato l'iperparametro perchè ci sono molte meno parole nel vocabolario
lda_title_neg=LDA(n_components=number_of_topics,max_iter=200,random_state=30,verbose=False)
new_lda_title_neg=lda_title_neg.fit_transform(Xtitleneg)

In [129]:
print("Ecco la matrice document topic: \n")
print(new_lda_title_neg, '\n')

Ecco la matrice document topic:

[[0.12044436 0.76778815 0.11176749]
 [0.16693183 0.66608095 0.16698722]
 [0.16722451 0.66543222 0.16734327]
 ...
 [0.16673992 0.66650495 0.16675513]
 [0.33333333 0.33333333 0.33333333]
 [0.16687761 0.66620059 0.1669218 ]]

In [130]:
print("Ecco ora la matrice topic word: \n")
j=0
for i in range (len(lda_title_neg.components_)):
   print(f"topic {j+1}: {lda_title_neg.components_[i]}")
   print("\n")
   j=j+1

Ecco ora la matrice topic word:

topic 1: [ 0.33555638  0.33555641  0.33512103  1.30466297  0.33524329  0.33495685
 16.3159862   0.33489324  0.33488616  0.3348922   4.32979559  0.34607519
  3.3298391   0.3354934   0.36119019  2.33123187  2.32922742  0.36437072
  0.35940092  0.3350409   9.32810222  0.3350757   0.33528927  2.32958064
  9.31635933  0.33560611  2.29008807  0.33473746  3.32787369  2.33087636
  2.32959869  2.32922737  0.33517557  0.33419908  0.33544165  0.33534509
  2.32966347  0.33509303  7.44448279  0.33436863  0.34912079  0.3351748
  3.27509324  1.32297883  4.3296697   0.33436863  0.33555637  0.33495859
  1.25912002  0.34025577  0.35060751  0.33549339  0.33534508  0.33456218
  0.33555638  0.33465134  3.32787367  4.31365969  3.33030957  0.33441088
  0.33555643  0.33555638  2.28940406  2.32770625  0.33510036  4.3279588
  4.32931164  0.33510201  0.33500197  0.33534508  2.32770631  0.33500234
  1.32898871  0.33432399  0.33493876  0.34944491  2.3296259   0.3355564
  3.20356405  0.36517459  0.33495846  0.33952257  1.34825669  5.31789461]


topic 2: [ 2.32841727  2.32841718  2.32956527  2.35931995  0.33542442  2.32974612
  0.34138907  4.31581859  0.33494772  0.33503935  0.33496063  4.31802745
  0.33499429  3.32855923  0.33500128  0.33452952  0.33528406  2.30028052
  0.33495921  0.33516182  0.33581933 14.32948678  0.33547543  0.3352872
  0.33523395  2.28883233  0.37356919  0.34035434  0.33592691  0.33465449
  0.3351533   0.33528406  4.32926393  2.33143848  5.32867554  0.33553748
  0.33506005  4.32945471  0.35070685  2.33104727  0.33471729  4.32926569
  0.3357165   1.34090065  0.33506444  2.33104727  2.32841727  2.3297403
  3.40605872  0.33508259  3.31345346  3.32855924  0.33553746  3.33071054
  2.3284173   0.339297    0.33592692  0.33520934  0.33485997  0.33419263
  2.32841715  2.3284173   0.37424656  0.33600556  2.29519465  0.33588686
  0.33520346  2.29518885  0.33515999  0.33553745  0.33600556  0.34631384
  1.33587806  4.33114781  0.33509093  0.33492328  0.33506248  2.32841725
  0.33593319  2.29875214  2.3297422   0.33493821  1.31637721  0.33520568]


topic 3: [0.33602635 0.33602641 0.3353137  0.33601708 5.32933229 0.33529704
 0.34262473 0.34928817 2.33016612 6.33006845 0.33524378 0.33589736
 0.33516661 0.33594738 2.30380853 0.33423861 0.33548852 0.33534876
 2.30563986 4.32979728 0.33607845 0.33543753 3.32923529 0.33513217
 0.34840672 0.37556156 0.33634274 7.32490821 0.3361994  0.33446915
 0.33524801 0.33548857 0.33556049 0.33436243 0.33588281 2.32911743
 0.33527648 0.33545226 3.20481037 0.3345841  3.31616193 0.33555951
 2.38919025 0.33612052 0.33526587 0.3345841  0.33602635 0.33530111
 0.33482125 7.32466165 0.33593903 0.33594737 2.32911746 0.33472728
 0.33602632 9.32605166 0.33619941 0.35113098 0.33483046 2.33139649
 0.33602642 0.33602632 0.33634938 0.33628819 0.36970499 0.33615434
 0.33548491 0.36970914 4.32983804 2.32911748 0.33628813 4.31868381
 0.33513323 0.3345282  3.32997031 3.31563182 0.33531162 0.33602635
 4.46050277 0.33607326 0.33529934 8.32553922 0.3353661  0.34689971]

In [131]:
print(f"La probabilità che la parola {title_feature_neg[74]} appartenga al topic {len(lda_title_neg.components_)} è {lda_title_neg.components_[2][74]/ lda_title_neg.components_[2].sum()} ")

La probabilità che la parola trascurare appartenga al topic 3 è 0.028417734333520638

In [132]:
max=8
for index, topic in enumerate(lda_title_neg.components_):
    # stampiamo gli indici delle prime 10 parole più popolari, usiamo argsort() per ordinarle in senso crescente,
    # quindi prenderemo gli ultimi 10 indici, denotando l'intervallo come [-10:]
    print("\nTOPIC %d - indici delle %d parole più popolari" % (index+1, max))
    print([i for i in topic.argsort()[-max:]])

    # utilizziamo il dizionario per trovare le parole in base agli indici
    print("\nTOPIC %d - %d parole più popolari (ordinate crescenti)" % (index+1, max))
    print([title_feature_neg[i] for i in topic.argsort()[-max:]])

    print('______________________________________________________________________________')

TOPIC 1 - indici delle 8 parole più popolari
[np.int64(66), np.int64(44), np.int64(10), np.int64(83), np.int64(38), np.int64(24), np.int64(20), np.int64(6)]

TOPIC 1 - 8 parole più popolari (ordinate crescenti)
['sopravvalutato', 'navigli', 'canale', 'zona', 'milano', 'duomo', 'deludere', 'bello']
______________________________________________________________________________

TOPIC 2 - indici delle 8 parole più popolari
[np.int64(7), np.int64(11), np.int64(32), np.int64(41), np.int64(37), np.int64(73), np.int64(34), np.int64(21)]

TOPIC 2 - 8 parole più popolari (ordinate crescenti)
['berlino', 'caos', 'locale', 'muro', 'migliore', 'totale', 'mah', 'delusione']
______________________________________________________________________________

TOPIC 3 - indici delle 8 parole più popolari
[np.int64(68), np.int64(78), np.int64(4), np.int64(9), np.int64(49), np.int64(27), np.int64(81), np.int64(55)]

TOPIC 3 - 8 parole più popolari (ordinate crescenti)
['sporco', 'vedere', 'aspettare', 'brutto', 'organizzazione', 'esperienza', 'visita', 'pessimo']
______________________________________________________________________________

* Il modello non è stato molto efficace per scopi di sentiment classification :

Seppure alcune parole che esprimono polarità sono state individuate come parole chiave dei vari topic, queste non permettono di distinguere bene quali sono stati gli aspetti positivi e quelli negativi riscontrati dagli utenti.
Le ragioni si possono attribuire alle seguenti:
 * pochi titoli disponibili per quanto riguarda le recensioni negative
 * Titoli molto brevi

# LDA con codifica Tf-Idf

* Ricreiamo il modello usando questa volta la codifica tf-Idf

In [133]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [134]:
tfidf=TfidfVectorizer(max_features=15000,stop_words=stopwords_finali,min_df=2,max_df=1000)
X2=tfidf.fit_transform(corpus_cleam)
X2.shape

(20058, 6769)

In [135]:
tfidf_features = tfidf.get_feature_names_out()
print("vediamo tutte le features: ", tfidf_features,'\n')
print("vediamo una decina di features: \n", tfidf_features[1000:1010])
print("vediamo la feature n.1245: ", tfidf_features[245])

vediamo tutte le features:  ['abbagliare' 'abbandonare' 'abbandonata' ... 'zoo' 'zoom' 'ztl']

vediamo una decina di features:
 ['capitello' 'capitolo' 'capo' 'capodanno' 'capogiro' 'capolavoro'
 'capolinea' 'capolino' 'capoluogo' 'cappa']
vediamo la feature n.1245:  america

* Soliti 5-6 minuti per l'esecuzione della cella

In [136]:
n_topics=8
lda_tfidf=LDA(n_components=n_topics,max_iter=150,verbose=False,random_state=31)
new_lda_tfidf=lda_tfidf.fit_transform(X2)

In [137]:
print(f"Ecco la matrice document topic: \n")
print(new_lda_tfidf, '\n')

Ecco la matrice document topic:

[[0.0253017  0.57520745 0.27268309 ... 0.02529873 0.02527344 0.025279  ]
 [0.03709326 0.03707722 0.5553013  ... 0.03713885 0.03707466 0.03708863]
 [0.02424864 0.7868354  0.02421781 ... 0.02422284 0.0242501  0.02422444]
 ...
 [0.02839386 0.02838576 0.801275   ... 0.02838882 0.02838084 0.02838851]
 [0.03550765 0.03551646 0.03551144 ... 0.03551205 0.44061803 0.34625525]
 [0.0289213  0.79759676 0.02891781 ... 0.02891054 0.02890326 0.02890382]]

In [138]:
print(f"Ecco ora la matrice topic word: \n")
j=0
for i in range (len(lda_tfidf.components_)):
   print(f"topic {j+1}: {lda_tfidf.components_[i]}")
   j+=1
   print("\n")

print(f"Questa matrice ha dimensioni {lda_tfidf.components_.shape}")

Ecco ora la matrice topic word:

topic 1: [ 0.12501111  2.18812206  0.12500002 ... 89.370671    1.17273365
  0.35921132]


topic 2: [0.12500006 0.12556689 0.70861057 ... 0.12503568 0.12500006 0.12669444]


topic 3: [0.12517907 0.12508107 0.12500162 ... 0.12504292 0.12500008 0.68544573]


topic 4: [0.12508319 0.12512346 0.12500004 ... 0.12500982 0.12500009 0.12500042]


topic 5: [4.04704869 1.66254008 0.12500003 ... 0.12501266 0.12500007 0.12500029]


topic 6: [0.1250001  0.12529102 0.12500005 ... 0.12501022 0.12500011 0.12605868]


topic 7: [0.12500527 4.46901949 0.12503539 ... 0.1250729  0.12500023 0.12500106]


topic 8: [0.12500748 0.12512275 0.12500004 ... 0.12502728 0.12506941 0.39230323]


Questa matrice ha dimensioni (8, 6769)

In [126]:
max=8
for index, topic in enumerate(lda_tfidf.components_):
    # stampiamo gli indici delle prime 10 parole più popolari, usiamo argsort() per ordinarle in senso crescente,
    # quindi prenderemo gli ultimi 10 indici, denotando l'intervallo come [-10:]
    print("\nTOPIC %d - indici delle %d parole più popolari" % (index+1, max))
    print([i for i in topic.argsort()[-max:]])

    # utilizziamo il dizionario per trovare le parole in base agli indici
    print("\nTOPIC %d - %d parole più popolari (ordinate crescenti)" % (index+1, max))
    print([tfidf_features[i] for i in topic.argsort()[-max:]])

    print('______________________________________________________________________________')

TOPIC 1 - indici delle 8 parole più popolari
[np.int64(4602), np.int64(2248), np.int64(3855), np.int64(5934), np.int64(3165), np.int64(585), np.int64(2421), np.int64(1311)]

TOPIC 1 - 8 parole più popolari (ordinate crescenti)
['primavera', 'estate', 'neve', 'stagione', 'inverno', 'autunno', 'film', 'colore']
______________________________________________________________________________

TOPIC 2 - indici delle 8 parole più popolari
[np.int64(2631), np.int64(3832), np.int64(3831), np.int64(346), np.int64(670), np.int64(5547), np.int64(5171), np.int64(3347)]

TOPIC 2 - 8 parole più popolari (ordinate crescenti)
['gente', 'naviglio', 'navigli', 'aperitivo', 'bar', 'sera', 'ristorante', 'locale']
______________________________________________________________________________

TOPIC 3 - indici delle 8 parole più popolari
[np.int64(3240), np.int64(5422), np.int64(3239), np.int64(2775), np.int64(2703), np.int64(4446), np.int64(772), np.int64(2700)]

TOPIC 3 - 8 parole più popolari (ordinate crescenti)
['lago', 'scoiattolo', 'laghetto', 'grattacielo', 'giro', 'polmone', 'bicicletta', 'girare']
______________________________________________________________________________

TOPIC 4 - indici delle 8 parole più popolari
[np.int64(5065), np.int64(721), np.int64(3399), np.int64(1574), np.int64(6283), np.int64(2684), np.int64(6694), np.int64(5666)]

TOPIC 4 - 8 parole più popolari (ordinate crescenti)
['rimanere', 'bellezza', 'luino', 'coro', 'touring', 'gioiello', 'volontario', 'sistina']
______________________________________________________________________________

TOPIC 5 - indici delle 8 parole più popolari
[np.int64(1172), np.int64(2511), np.int64(852), np.int64(4177), np.int64(4465), np.int64(3789), np.int64(4557), np.int64(1690)]

TOPIC 5 - 8 parole più popolari (ordinate crescenti)
['chilometro', 'foto', 'brandeburgo', 'parlamento', 'porta', 'murales', 'prenotare', 'cupola']
______________________________________________________________________________

TOPIC 6 - indici delle 8 parole più popolari
[np.int64(2812), np.int64(5300), np.int64(3437), np.int64(6186), np.int64(3062), np.int64(1271), np.int64(2417), np.int64(779)]

TOPIC 6 - 8 parole più popolari (ordinate crescenti)
['guida', 'salire', 'madrid', 'terrazza', 'ingresso', 'coda', 'fila', 'biglietto']
______________________________________________________________________________

TOPIC 7 - indici delle 8 parole più popolari
[np.int64(1082), np.int64(3204), np.int64(3435), np.int64(721), np.int64(2811), np.int64(3753), np.int64(5637), np.int64(4364)]

TOPIC 7 - 8 parole più popolari (ordinate crescenti)
['cattedrale', 'italia', 'madonnina', 'bellezza', 'guglia', 'monumento', 'simbolo', 'piazza']
______________________________________________________________________________

TOPIC 8 - indici delle 8 parole più popolari
[np.int64(3580), np.int64(1106), np.int64(3983), np.int64(1881), np.int64(2511), np.int64(799), np.int64(993), np.int64(3582)]

TOPIC 8 - 8 parole più popolari (ordinate crescenti)
['memoria', 'cemento', 'olocausto', 'dimenticare', 'foto', 'blocco', 'capire', 'memoriale']
______________________________________________________________________________

* I risultati ottenuti con i due diversi tipi di codifica del corpus di documenti sono differenti (a parità di operazioni di processamento preliminari effettuate sui testi)
* topic differenti da quelli scoperti in precedenza :  
   * 1 Stagioni e Clima
   * 8 Shoah

# Topic Modelling con Gensim

* Riproponiamo di seguito la routine completa spiegata nei notebook condivisi del corso

In [139]:
from gensim.corpora import Dictionary
from gensim.models.ldamodel import LdaModel
from gensim.utils import simple_preprocess

In [129]:
nltk.download('wordnet')

[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [141]:
lemmatizer=nltk.stem.WordNetLemmatizer()

In [241]:
def preprocess (text):
  tokens=[]
  for token in simple_preprocess(text):
   if(token not in stopwords_finali):   #come insieme per le stopwords manteniamo quello arricchito con l'aggiunta delle parole che 'intensificano'
     tokens.append(lemmatizer.lemmatize(token, pos='v'))
  return tokens

In [242]:
df_positive=df[df["stars"]>=3]

* Per provare a migliorare il risultato sui titoli, combiniamo la pipeline di processamento di spacy con il 'simple_preprocess' di gensim

In [243]:
def clean1_titles(text):
    doc = nlp(text.lower())
    token_puliti = []

    for tok in doc:
        if tok.is_stop: #rimozione stopwords
            continue
        if tok.pos_ in ["ADV"]:  #proviamo a mantenere solo aggettivi ma non avverbi
            continue
        if tok.is_punct or tok.is_space or tok.like_num: #rimozione spazi punteggiatura e numeri(anche scritti a lettere)
            continue
        if not tok.is_alpha: #manenimento token che contengono solo lettere
            continue
        if not zipf_frequency(tok.lemma_, 'it') > 2: #rimozione parole troppo rare
            continue

        token_puliti.append(tok.lemma_) # lemmatizzazione

    return " ".join(token_puliti)

In [244]:
df_positive["title"]=[clean1_titles(title) for title in df_positive["title"]]

In [245]:
df_positive["title_preprocessed"]=df_positive["title"].map(preprocess)
df_positive.head(20)

,Unnamed: 0,comment,title,date,name,stars,comment_preprocessed,title_preprocessed
0,0,interessante sera trambusto età sacco bar rist...,zona canal,26 ottobre 2016,gfdmmad,5.0,"[interessante, sera, trambusto, età, sacco, ba...","[zona, canal]"
1,1,organizzare coda entrata piantine visita perco...,visita piacere,26 aprile 2019,Diabolik-Eva-014,5.0,"[organizzare, coda, entrata, piantine, visita,...","[visita, piacere]"
2,2,amico o expo strada il navigli porto darsena r...,vedere Milano,18 novembre 2018,O5262KGchrisd,5.0,"[amico, expo, strada, navigli, porto, darsena,...",[milano]
3,3,visitare duomo Milano madonnina guglia esperie...,duomo affascinante,7 agosto 2019,Babellina,5.0,"[visitare, duomo, milano, madonnina, guglia, e...","[duomo, affascinante]"
4,4,vista duomo uscita metro togliere fiato il lav...,eccezionale,9 dicembre 2019,Nik804,5.0,"[vista, duomo, uscita, metro, togliere, fiato,...",[eccezionale]
5,5,Milano visitare chiesa cuore Milano passo univ...,visita imperdibile,21 aprile 2017,matteodifelice,5.0,"[milano, visitare, chiesa, cuore, milano, pass...","[visita, imperdibile]"
6,6,tenere passeggiare stare,oasi caos,23 dicembre 2017,Ghert2015,4.0,"[tenere, passeggiare, stare]","[oasi, caos]"
7,7,creare traccia passato impedire adeguare si es...,sospendere passato presente,10 febbraio 2017,bobmonica,5.0,"[creare, traccia, passato, impedire, adeguare,...","[sospendere, passato, presente]"
8,8,parola descrivere bellezza parco passeggiare c...,imperdibile,6 novembre 2016,Duecuorieunaciccions,5.0,"[parola, descrivere, bellezza, parco, passeggi...",[imperdibile]
9,9,polmone simbolo New York consigliare passeggia...,passeggiata obbligatorio,23 novembre 2017,CDam7,5.0,"[polmone, simbolo, new, york, consigliare, pas...","[passeggiata, obbligatorio]"
11,11,stagione girare prendere barchetta rema laghet...,domenica parco,7 ottobre 2017,Elisabetta P,5.0,"[stagione, girare, prendere, barchetta, rema, ...","[domenica, parco]"
12,12,attrazione vedere ingresso audio guida edifici...,visita Berlino,17 marzo 2019,V586OIdavide,4.0,"[attrazione, vedere, ingresso, audio, guida, e...","[visita, berlino]"
13,13,arrivare cogliere desolazione memoriale cammin...,smarrimento ragione,5 aprile 2019,Aurora P,4.0,"[arrivare, cogliere, desolazione, memoriale, c...","[smarrimento, ragione]"
14,14,il sale frescura picnic leggere il bimbo anzia...,parco,6 febbraio 2017,Saverio Ammendola,5.0,"[sale, frescura, picnic, leggere, bimbo, anzia...",[parco]
16,16,caravaggio Velasquez raffaello rene goya amant...,bello,30 settembre 2018,viaggiatorelowcost,5.0,"[caravaggio, velasquez, raffaello, rene, goya,...",[]
17,17,zona Milano visitare trovandola sera vedere porta,,25 gennaio 2016,Nocciolino72,3.0,"[zona, milano, visitare, trovandola, sera, ved...",[]
18,18,parco trovare spazio impegnare noleggiare gira...,relax sport,14 agosto 2017,Fram05,5.0,"[parco, trovare, spazio, impegnare, noleggiare...","[relax, sport]"
19,19,il giro poco locale moda orario cè troppo conf...,il,23 settembre 2018,Vincenzo,3.0,"[giro, poco, locale, moda, orario, cè, troppo,...",[]
20,20,credere parco cittadino polmone ny interno mol...,minuto,11 settembre 2015,sergio pigoli p,5.0,"[credere, parco, cittadino, polmone, ny, inter...",[minuto]
21,21,rimanere varcare soglia esterno passaggio poco...,delizia occhio,14 ottobre 2018,lunina71,5.0,"[rimanere, varcare, soglia, esterno, passaggio...","[delizia, occhio]"

In [246]:
titles_p=df_positive["title_preprocessed"].values
print(titles_p.shape)

print(titles_p)
print("\n")
print(titles_p[:3])

(19710,)
[list(['zona', 'canal']) list(['visita', 'piacere']) list(['milano']) ...
 list(['museo']) list(['spettacolare', 'porta', 'simbolo', 'berlino'])
 list(['angolo', 'milano', 'perdere'])]


[list(['zona', 'canal']) list(['visita', 'piacere']) list(['milano'])]

In [247]:
dictionary=Dictionary(titles_p)
for token,id in dictionary.token2id.items():
  print(f"{token} : {id}")

canal : 0
zona : 1
piacere : 2
visita : 3
milano : 4
affascinante : 5
duomo : 6
eccezionale : 7
imperdibile : 8
caos : 9
oasi : 10
passato : 11
presente : 12
sospendere : 13
obbligatorio : 14
passeggiata : 15
domenica : 16
parco : 17
berlino : 18
ragione : 19
smarrimento : 20
relax : 21
sport : 22
minuto : 23
delizia : 24
occhio : 25
altro : 26
wow : 27
unico : 28
meraviglia : 29
meraviglioso : 30
stagione : 31
perdere : 32
gita : 33
gioiello : 34
visitare : 35
gestire : 36
guidare : 37
interessante : 38
surreale : 39
more : 40
wall : 41
età : 42
sbagliare : 43
cuore : 44
new : 45
verde : 46
york : 47
adorare : 48
city : 49
imponente : 50
museo : 51
ny : 52
simbolo : 53
cambiamento : 54
continuo : 55
inaspettato : 56
eccessivo : 57
grattacielo : 58
immenso : 59
caratteristico : 60
sorprendere : 61
natale : 62
pensavamo : 63
sorpresa : 64
pace : 65
superbo : 66
monumento : 67
corsa : 68
orario : 69
cappello : 70
sistina : 71
vero : 72
centro : 73
milanese : 74
movida : 75
faticoso : 76
sporco : 77
meta : 78
atmosfera : 79
gratuito : 80
tipico : 81
muro : 82
passeggiare : 83
passeggiato : 84
scoiattolo : 85
gradita : 86
sorpreso : 87
happy : 88
hour : 89
polmone : 90
aperto : 91
arte : 92
cielo : 93
galleria : 94
architettonico : 95
lasciatevi : 96
scappare : 97
romantico : 98
suggestivo : 99
scoperta : 100
life : 101
night : 102
alto : 103
ammirare : 104
navigli : 105
vintage : 106
inverno : 107
dipingere : 108
scrigno : 109
esperienza : 110
conoscere : 111
pere : 112
giro : 113
comune : 114
capire : 115
triste : 116
vicenda : 117
mancare : 118
fascino : 119
canale : 120
fila : 121
saltare : 122
cinquecentesco : 123
cultura : 124
insegna : 125
top : 126
fast : 127
free : 128
prado : 129
riflettere : 130
ombra : 131
turistico : 132
tempio : 133
chicca : 134
benessere : 135
mela : 136
paradiso : 137
spettacolare : 138
indicazione : 139
servire : 140
nyc : 141
capolavoro : 142
inimitabile : 143
bevanda : 144
pasto : 145
serale : 146
indimenticabile : 147
incantare : 148
tenere : 149
amare : 150
dicembre : 151
dispersivo : 152
central : 153
park : 154
tramonto : 155
colore : 156
esplosione : 157
esterno : 158
nascondere : 159
bice : 160
organizzato : 161
madrid : 162
viaggio : 163
appassionato : 164
quadro : 165
amico : 166
serata : 167
piccolo : 168
adorabile : 169
risorge : 170
vecchio : 171
giornata : 172
dimenticare : 173
circondare : 174
nic : 175
pic : 176
sole : 177
angolo : 178
scoprire : 179
tappa : 180
andare : 181
migliore : 182
sconosciuto : 183
mr : 184
wonderland : 185
bici : 186
john : 187
lennon : 188
orma : 189
spagna : 190
viaggiare : 191
east : 192
gallery : 193
side : 194
fiato : 195
rimanere : 196
chiesa : 197
maurizio : 198
monastero : 199
san : 200
maratona : 201
nascosto : 202
tesoro : 203
emozionale : 204
bicicletta : 205
divertimento : 206
spettacolo : 207
aereo : 208
mamma : 209
manhattan : 210
famoso : 211
maestoso : 212
piano : 213
cena : 214
honeymoon : 215
newyork : 216
ricco : 217
classico : 218
aperitivo : 219
animato : 220
snobbare : 221
particolarità : 222
splendido : 223
importante : 224
nazione : 225
rilassare : 226
volere : 227
credere : 228
affascinare : 229
punto : 230
vista : 231
passaggio : 232
fisso : 233
caldo : 234
favoloso : 235
rilassante : 236
gioia : 237
salute : 238
fortissimo : 239
serenità : 240
girare : 241
aspettare : 242
alba : 243
luce : 244
speciale : 245
milan : 246
immancabile : 247
storia : 248
end : 249
week : 250
cappe : 251
aspettativa : 252
confermato : 253
fotografico : 254
rassegna : 255
shoah : 256
organizzazione : 257
tedesco : 258
europa : 259
brivido : 260
eccellenza : 261
grandioso : 262
esplorare : 263
acqua : 264
area : 265
diventare : 266
guglia : 267
vacanza : 268
giovane : 269
must : 270
bocca : 271
cattedrale : 272
borgo : 273
caratteristica : 274
super : 275
emozione : 276
migliorare : 277
mostra : 278
percorso : 279
cancellare : 280
possibile : 281
grigio : 282
buzz : 283
fantasticare : 284
gente : 285
turista : 286
immaginare : 287
gusto : 288
carino : 289
irrinunciabile : 290
sogno : 291
goya : 292
biglietto : 293
cemento : 294
film : 295
obbligare : 296
assoluto : 297
sublime : 298
drink : 299
graffito : 300
rovinare : 301
valorizzato : 302
eccelso : 303
frequentato : 304
terrazza : 305
teatro : 306
affresco : 307
angola : 308
avviso : 309
parola : 310
parlamento : 311
pomeriggio : 312
difficile : 313
pensare : 314
tornare : 315
mito : 316
ok : 317
canottaggio : 318
naviglio : 319
caotico : 320
sentire : 321
famiglia : 322
architettura : 323
unicum : 324
location : 325
igienico : 326
pubblico : 327
wc : 328
significativo : 329
dare : 330
scontare : 331
provare : 332
barca : 333
rema : 334
spazio : 335
esposizione : 336
estate : 337
vivere : 338
luino : 339
corsetto : 340
quartiere : 341
brandeburgo : 342
portare : 343
cupola : 344
notturna : 345
impressionante : 346
massa : 347
notte : 348
sabato : 349
umanità : 350
diverso : 351
monumentale : 352
pedalare : 353
libertà : 354
commuovere : 355
crimine : 356
testimonianza : 357
ricordare : 358
pittura : 359
spagnolo : 360
velasquez : 361
est : 362
immersione : 363
estivo : 364
ideale : 365
passare : 366
cibo : 367
notturno : 368
passo : 369
funzionare : 370
impossibile : 371
influenza : 372
tripudio : 373
vuoto : 374
enorme : 375
posto : 376
silenzio : 377
break : 378
coppia : 379
sera : 380
comodo : 381
frequentare : 382
raggiungere : 383
lombardo : 384
pezzo : 385
newyorkese : 386
vincolo : 387
esistere : 388
divisione : 389
neve : 390
fiume : 391
realtà : 392
pausa : 393
inferno : 394
opera : 395
trasformare : 396
totale : 397
conosciuto : 398
formidabile : 399
raccolta : 400
operare : 401
pattinare : 402
festa : 403
pronto : 404
quiete : 405
interno : 406
restauro : 407
strepitoso : 408
pulsante : 409
amaro : 410
ricordo : 411
cugino : 412
pazzesco : 413
musica : 414
vino : 415
camminata : 416
domenicale : 417
espositivo : 418
pinacoteca : 419
nonno : 420
aria : 421
puro : 422
fascinoso : 423
felicità : 424
tranquillità : 425
straordinario : 426
informazione : 427
creatività : 428
attento : 429
sacco : 430
zanzara : 431
grado : 432
mozzafiato : 433
panorama : 434
biglietteria : 435
concludere : 436
home : 437
sweet : 438
intero : 439
intenso : 440
economico : 441
tranquillo : 442
dire : 443
impazzire : 444
bellezza : 445
inalazione : 446
de : 447
dom : 448
el : 449
costruzione : 450
splendore : 451
foto : 452
navi : 453
secolo : 454
offrire : 455
nuovo : 456
rinascita : 457
figlio : 458
run : 459
orgoglio : 460
discutibile : 461
gestione : 462
passeggio : 463
consigliare : 464
preghiera : 465
educare : 466
vitalità : 467
street : 468
arrogante : 469
gentile : 470
personale : 471
boccata : 472
romanticismo : 473
newyorchese : 474
ossigeno : 475
pò : 476
mercatini : 477
evoluzione : 478
tradizione : 479
stupore : 480
obbligato : 481
maja : 482
muy : 483
noto : 484
laghetto : 485
storico : 486
abito : 487
monaco : 488
amante : 489
memoria : 490
jog : 491
jhon : 492
mattinata : 493
effetto : 494
toccante : 495
restare : 496
ripasso : 497
utile : 498
natura : 499
cambiare : 500
metropoli : 501
mare : 502
piazza : 503
imprescindibile : 504
inebriante : 505
visione : 506
rigenerare : 507
meravigliare : 508
mese : 509
ultimo : 510
sconvolgente : 511
confusionario : 512
inutile : 513
isola : 514
ebreo : 515
memoriale : 516
olocausto : 517
simbolismo : 518
mondiale : 519
narrare : 520
strutturare : 521
dedicare : 522
indescrivibile : 523
bere : 524
immensità : 525
aprire : 526
significato : 527
moderno : 528
valorizza : 529
ia : 530
by : 531
arca : 532
noè : 533
ambrogio : 534
divinita : 535
ciò : 536
affascinato : 537
maggiore : 538
it : 539
spasso : 540
zoo : 541
colorato : 542
entrai : 543
lasciare : 544
respect : 545
with : 546
coronare : 547
figo : 548
abitante : 549
dipinto : 550
parete : 551
sorprendente : 552
anatre : 553
centrale : 554
ghiaccia : 555
lago : 556
pittore : 557
bosco : 558
contesto : 559
vello : 560
appropria : 561
amsterdam : 562
spietata : 563
trascurare : 564
pulire : 565
spostare : 566
meritare : 567
nascosti : 568
trascorrere : 569
documentare : 570
guardare : 571
devastante : 572
navigabile : 573
nn : 574
artistico : 575
ritornare : 576
bisogno : 577
forte : 578
sensazione : 579
incanto : 580
attimo : 581
tetto : 582
greco : 583
obbligo : 584
qualsiasi : 585
natalizio : 586
murales : 587
camminare : 588
foresta : 589
luna : 590
gotico : 591
magnificenza : 592
mangiare : 593
discreto : 594
orrore : 595
las : 596
animare : 597
istituzione : 598
fragilità : 599
autunno : 600
locale : 601
italia : 602
pandemia : 603
roba : 604
peccare : 605
great : 606
autentico : 607
preferire : 608
permettere : 609
succedere : 610
vergogna : 611
infinito : 612
mille : 613
valorizzare : 614
stendhal : 615
nudo : 616
godere : 617
amore : 618
scorcio : 619
fabbrica : 620
artificiale : 621
affrescato : 622
disco : 623
impatto : 624
ingegneria : 625
beautiful : 626
capanna : 627
facciata : 628
forma : 629
bar : 630
ristorante : 631
alternativo : 632
venerdì : 633
nascosta : 634
magnifica : 635
previsione : 636
caffetteria : 637
interessare : 638
attraversamento : 639
ns : 640
incantato : 641
siii : 642
nazismo : 643
cosa : 644
interesse : 645
religione : 646
giardino : 647
carrozza : 648
mastodontico : 649
immaginario : 650
impagabile : 651
incasinare : 652
delizioso : 653
tour : 654
senso : 655
invernale : 656
rappresentativo : 657
europeo : 658
guidato : 659
urbano : 660
spritz : 661
stress : 662
pioggia : 663
simpatico : 664
tuffo : 665
casa : 666
ringhiera : 667
abitare : 668
anniversario : 669
art : 670
incontrare : 671
capodanno : 672
visualizzazione : 673
mattino : 674
colpo : 675
stomaco : 676
affittare : 677
romano : 678
delusione : 679
compleanno : 680
festeggiare : 681
brillante : 682
revival : 683
sguardo : 684
tragedia : 685
anonimo : 686
fermare : 687
curato : 688
celare : 689
novembre : 690
morte : 691
striscia : 692
eccellente : 693
imparare : 694
vivo : 695
luminoso : 696
visit : 697
paura : 698
berlinese : 699
luogo : 700
walk : 701
ingresso : 702
piena : 703
pazzesca : 704
sunset : 705
heaven : 706
gigante : 707
pietra : 708
copertura : 709
chiamare : 710
bundestag : 711
particolare : 712
goduria : 713
culto : 714
riflessione : 715
avere : 716
dovere : 717
salto : 718
inestimabile : 719
guida : 720
iconico : 721
reichstag : 722
bosso : 723
costo : 724
offerta : 725
pattinaggio : 726
pista : 727
maestosità : 728
sacro : 729
antico : 730
go : 731
realizzazione : 732
togliere : 733
strategico : 734
carico : 735
tristezza : 736
aggiungere : 737
rispetto : 738
energia : 739
iniezione : 740
veloce : 741
gioiellino : 742
edificio : 743
ostaggio : 744
popolo : 745
colpire : 746
ricamo : 747
fifth : 748
german : 749
important : 750
most : 751
of : 752
one : 753
symbol : 754
the : 755
attrazione : 756
settembre : 757
approfondire : 758
brunch : 759
colazione : 760
pranzo : 761
autunnale : 762
bike : 763
ridere : 764
mutare : 765
potsdam : 766
memorial : 767
mauro : 768
innamorare : 769
opulenza : 770
lavoro : 771
maurilio : 772
angosciante : 773
acquisto : 774
biglietti : 775
prevendita : 776
moda : 777
negozio : 778
potere : 779
simbolica : 780
semplicità : 781
dettaglio : 782
studiare : 783
day : 784
culturale : 785
pittoresco : 786
margine : 787
runner : 788
infinitamente : 789
kilometro : 790
sballo : 791
prenotazione : 792
prezzo : 793
inopportuno : 794
presenza : 795
immagine : 796
apericena : 797
regno : 798
viale : 799
macchia : 800
erba : 801
arrivare : 802
antipasto : 803
appendere : 804
principale : 805
scena : 806
ineguagliabile : 807
birra : 808
chiacchere : 809
sorseggiare : 810
mitico : 811
natalizia : 812
magia : 813
gigantesco : 814
completo : 815
okay : 816
favola : 817
scenario : 818
chiedere : 819
porto : 820
pensiero : 821
icona : 822
studente : 823
diluvio : 824
ape : 825
paragonabile : 826
scalare : 827
intendere : 828
italiano : 829
asciutto : 830
sinfonia : 831
calma : 832
charme : 833
pubblicizzare : 834
attuale : 835
ché : 836
intere : 837
grandissimo : 838
labirinto : 839
comprendere : 840
online : 841
darsena : 842
madonna : 843
sotterraneo : 844
commovente : 845
rettangolo : 846
dario : 847
grattacieli : 848
politica : 849
mattutino : 850
appuntamento : 851
esaltare : 852
paesaggio : 853
stridere : 854
cornice : 855
club : 856
volontario : 857
annoiare : 858
inimmaginabile : 859
fenomenale : 860
curioso : 861
raccontare : 862
madonnina : 863
sollevare : 864
spirito : 865
modo : 866
momento : 867
incontro : 868
capatina : 869
panoramico : 870
field : 871
design : 872
naturale : 873
vicino : 874
occasione : 875
semper : 876
leonardo : 877
terrore : 878
topografia : 879
germania : 880
solito : 881
risciò : 882
stanco : 883
frequentatore : 884
pieno : 885
prendere : 886
ingannare : 887
mappa : 888
notevole : 889
restaurato : 890
soddisfacente : 891
distretto : 892
rinascimentale : 893
pù : 894
pittorico : 895
idea : 896
deluso : 897
perla : 898
risistemare : 899
fondere : 900
comprare : 901
stancante : 902
prenotare : 903
appartenere : 904
libro : 905
consigliato : 906
basilica : 907
indispensabile : 908
magiare : 909
metro : 910
immensamente : 911
trovare : 912
ricostruzione : 913
re : 914
solenne : 915
vivace : 916
organizzare : 917
celebrato : 918
uggioso : 919
tappare : 920
trascurato : 921
fighe : 922
nascoste : 923
concentrato : 924
imponenza : 925
entusiasmare : 926
rigirare : 927
bianco : 928
primavera : 929
tocco : 930
dorato : 931
gabbia : 932
santo : 933
soggiorno : 934
colpa : 935
essere : 936
indicibile : 937
respirare : 938
amaze : 939
every : 940
doom : 941
avvolge : 942
cattura : 943
gradevole : 944
porta : 945
best : 946
navigo : 947
cavallo : 948
alpino : 949
boys : 950
magic : 951
time : 952
fondamentale : 953
riempie : 954
fondo : 955
assaggio : 956
entrata : 957
livello : 958
fatato : 959
fare : 960
stupende : 961
maggio : 962
wonderful : 963
fiabesco : 964
riorganizzare : 965
prestigioso : 966
sosta : 967
be : 968
good : 969
very : 970
fortuna : 971
dama : 972
rilassano : 973
pagare : 974
riguardare : 975
mattina : 976
nebbia : 977
meneghina : 978
rinascimento : 979
collazione : 980
ottavo : 981
ciop : 982
cip : 983
gastronomico : 984
cool : 985
accadere : 986
buio : 987
illuminare : 988
poesia : 989
meditare : 990
dubbio : 991
artista : 992
trionfo : 993
demoniaco : 994
figura : 995
essenziale : 996
bernardino : 997
coro : 998
iniziare : 999
antonomasia : 1000
sbalorditivo : 1001
differenza : 1002
notare : 1003
scolastico : 1004
bicycle : 1005
on : 1006
resto : 1007
columbus : 1008
detto : 1009
incomprensibile : 1010
er : 1011
inizio : 1012
perplessa : 1013
via : 1014
commentare : 1015
lento : 1016
scorrere : 1017
dio : 1018
giovanile : 1019
cappella : 1020
venezia : 1021
volare : 1022
struttura : 1023
pasqua : 1024
leggenda : 1025
mercato : 1026
prossimo : 1027
pulce : 1028
diurno : 1029
maestà : 1030
apprezzabile : 1031
bue : 1032
tardivo : 1033
corsetta : 1034
fazzoletto : 1035
skyline : 1036
stendere : 1037
periodo : 1038
ristrutturare : 1039
svago : 1040
giusto : 1041
anima : 1042
immensa : 1043
tavola : 1044
piccolissimo : 1045
rifare : 1046
foschia : 1047
salire : 1048
noleggio : 1049
fatica : 1050
facile : 1051
muovere : 1052
sala : 1053
pomeridiano : 1054
segreto : 1055
fateci : 1056
casuale : 1057
ballare : 1058
stella : 1059
usa : 1060
rifletto : 1061
sublima : 1062
compagnia : 1063
seriale : 1064
gemma : 1065
sicuro : 1066
impressionare : 1067
conquistare : 1068
finte : 1069
prescindere : 1070
rendere : 1071
movimento : 1072
freddo : 1073
spiazzante : 1074
bambino : 1075
chilometro : 1076
avvento : 1077
deludono : 1078
mercatino : 1079
chiostro : 1080
can : 1081
place : 1082
where : 1083
you : 1084
your : 1085
necessario : 1086
spiritualità : 1087
avverare : 1088
caro : 1089
scuola : 1090
vine : 1091
cp : 1092
multifunzionale : 1093
dimenticato : 1094
cell : 1095
pc : 1096
scattare : 1097
sfondo : 1098
preferiti : 1099
parl : 1100
ferragosto : 1101
corso : 1102
remember : 1103
uscire : 1104
weekend : 1105
berliner : 1106
toccare : 1107
giretto : 1108
inverosimile : 1109
concerto : 1110
programmato : 1111
cittadino : 1112
bela : 1113
calmo : 1114
recensione : 1115
sconfinare : 1116
crudelta : 1117
umano : 1118
esperto : 1119
strada : 1120
sportivo : 1121
insuperabile : 1122
frizzante : 1123
ridondante : 1124
inserimento : 1125
sapiente : 1126
ladro : 1127
folklore : 1128
nostalgia : 1129
immerso : 1130
soleggiato : 1131
silenzioso : 1132
secondo : 1133
brullo : 1134
curare : 1135
uguale : 1136
bohemian : 1137
sognare : 1138
memorabile : 1139
affermazione : 1140
sì : 1141
dividere : 1142
prezioso : 1143
scoppio : 1144
pulizia : 1145
mirabile : 1146
ordine : 1147
sparso : 1148
monito : 1149
capitolo : 1150
full : 1151
immersion : 1152
profondo : 1153
gestapo : 1154
quartier : 1155
infanzia : 1156
velocità : 1157
greenpeace : 1158
attivo : 1159
palma : 1160
stringere : 1161
classe : 1162
organico : 1163
caffè : 1164
sviluppo : 1165
autumn : 1166
sù : 1167
rallentare : 1168
ritmo : 1169
componente : 1170
positivo : 1171
veneranda : 1172
acquario : 1173
agghiacciante : 1174
settimana : 1175
assurdo : 1176
lungo : 1177
capello : 1178
spiegare : 1179
salvare : 1180
stupire : 1181
impiegare : 1182
papà : 1183
arco : 1184
agenzia : 1185
erika : 1186
unire : 1187
complesso : 1188
movimentare : 1189
panzerotto : 1190
politico : 1191
pubblicizzato : 1192
calde : 1193
giocare : 1194
polmonare : 1195
antiquariato : 1196
stupefatto : 1197
contemporaneo : 1198
attenzione : 1199
internazionale : 1200
democrazia : 1201
ultima : 1202
eleganza : 1203
ampio : 1204
didascalia : 1205
gauche : 1206
sopratutto : 1207
culmine : 1208
dream : 1209
mecca : 1210
errato : 1211
map : 1212
ordinare : 1213
tosta : 1214
misterioso : 1215
tratto : 1216
trafficato : 1217
uccidere : 1218
occupare : 1219
fugare : 1220
miele : 1221
big : 1222
fantastica : 1223
bien : 1224
messa : 1225
une : 1226
lacrima : 1227
merito : 1228
dolce : 1229
metà : 1230
traffico : 1231
ammirazione : 1232
esaltante : 1233
entusiasmante : 1234
geniale : 1235
rito : 1236
migliorabile : 1237
gradire : 1238
ritorno : 1239
navigabili : 1240
navigare : 1241
speranza : 1242
piacevolissimo : 1243
origine : 1244
fiaba : 1245
fantasia : 1246
libero : 1247
sfogo : 1248
pedonale : 1249
line : 1250
istruttivo : 1251
maniera : 1252
restaurare : 1253
infinità : 1254
reperto : 1255
sentì : 1256
questione : 1257
specchi : 1258
genocidio : 1259
allucinogeno : 1260
casino : 1261
divertente : 1262
ricoprire : 1263
trarre : 1264
volgere : 1265
green : 1266
heart : 1267
congelare : 1268
ideatore : 1269
coinvolgimento : 1270
uomo : 1271
ritrovo : 1272
consiglio : 1273
old : 1274
italy : 1275
make : 1276
rappresentare : 1277
molesto : 1278
do : 1279
to : 1280
colorare : 1281
paragone : 1282
sereno : 1283
riaprire : 1284
lassù : 1285
basilico : 1286
fotografare : 1287
venire : 1288
capella : 1289
impalcatura : 1290
cosiddetto : 1291
segno : 1292
sopravvalutato : 1293
cinematografico : 1294
set : 1295
integrativo : 1296
patrimonio : 1297
intenditore : 1298
frenesia : 1299
trendy : 1300
lezione : 1301
macchina : 1302
pessimo : 1303
movimentata : 1304
rumorosa : 1305
sontuoso : 1306
cromatico : 1307
rinnovare : 1308
leggero : 1309
lirica : 1310
impressione : 1311
accogliente : 1312
delirio : 1313
trasmettere : 1314
deludere : 1315
dodicesimo : 1316
atmosfere : 1317
battello : 1318
pavese : 1319
collaboratore : 1320
lombardia : 1321
straniamento : 1322
sbalordire : 1323
iconografia : 1324
mezzo : 1325
godibile : 1326
soggezione : 1327
pesante : 1328
piene : 1329
preferito : 1330
scenico : 1331
genere : 1332
trappola : 1333
mettere : 1334
iconografico : 1335
verace : 1336
salvezza : 1337
visitatore : 1338
disordinato : 1339
frenetico : 1340
normalità : 1341
collezione : 1342
ciclabile : 1343
dimesso : 1344
sapere : 1345
tacchino : 1346
love : 1347
naso : 1348
apprezzare : 1349
pelle : 1350
america : 1351
mondano : 1352
carinissimo : 1353
problema : 1354
piace : 1355
influencer : 1356
comprensibile : 1357
tela : 1358
pedalata : 1359
evocativo : 1360
riflessivo : 1361
piazzare : 1362
finire : 1363
accesso : 1364

In [248]:
dictionary.filter_extremes(no_below=3,no_above=0.6,keep_n=2500)

In [249]:
X3=[dictionary.doc2bow(title) for title in titles_p]
print(f"Ecco i primi 3 titoli in formato bow: \n {X3[:3]}")

Ecco i primi 3 titoli in formato bow:
 [[(0, 1), (1, 1)], [(2, 1), (3, 1)], [(4, 1)]]

In [250]:
from gensim.models import LdaMulticore
lda_gensim_p=LdaMulticore(X3,num_topics=5,id2word=dictionary,passes=250,workers=3)
#4 minuti

In [251]:
for index,topic in lda_gensim_p.print_topics():
  print("\nTopic %d - parole chiave" % (index+1))
  print(topic)

Topic 1 - parole chiave
0.083*"meraviglioso" + 0.052*"museo" + 0.039*"passeggiata" + 0.038*"unico" + 0.033*"relax" + 0.031*"suggestivo" + 0.028*"milanese" + 0.023*"esperienza" + 0.021*"chiesa" + 0.021*"visita"

Topic 2 - parole chiave
0.071*"park" + 0.060*"central" + 0.047*"spettacolare" + 0.045*"berlino" + 0.040*"interessante" + 0.032*"spettacolo" + 0.032*"splendido" + 0.028*"film" + 0.022*"enorme" + 0.020*"giro"

Topic 3 - parole chiave
0.093*"verde" + 0.065*"polmone" + 0.051*"storia" + 0.051*"meraviglia" + 0.046*"imperdibile" + 0.044*"visita" + 0.029*"oasi" + 0.022*"muro" + 0.018*"centro" + 0.017*"manhattan"

Topic 4 - parole chiave
0.129*"milano" + 0.072*"perdere" + 0.055*"visitare" + 0.052*"passeggiare" + 0.048*"new" + 0.047*"york" + 0.038*"cuore" + 0.025*"simbolo" + 0.024*"arte" + 0.019*"capolavoro"

Topic 5 - parole chiave
0.088*"milano" + 0.087*"parco" + 0.076*"duomo" + 0.056*"sistina" + 0.047*"gioiello" + 0.041*"cappello" + 0.039*"immenso" + 0.033*"tappa" + 0.024*"maestoso" + 0.019*"obbligatorio"

In [252]:
import pyLDAvis.gensim
lda_gensim_p_vis=pyLDAvis.gensim.prepare(lda_gensim_p,X3 ,dictionary, mds='tsne')
pyLDAvis.display(lda_gensim_p_vis)

* Passiamo alle recensioni negative

In [253]:
df_negative=df[df["stars"]<3]

In [254]:
df_negative["title"]=[clean1_titles(title) for title in df_negative["title"]]

In [255]:
df_negative["title_preprocessed"]=df_negative["title"].map(preprocess)
df_negative

,Unnamed: 0,comment,title,date,name,stars,comment_preprocessed,title_preprocessed
10,10,visitare milano periodo Natale mille rendere p...,gioco acqua natalizio navigazione musicale,15 dicembre 2019,Alessandra d,1.0,"[visitare, milano, periodo, natale, mille, ren...","[gioco, acqua, natalizio, navigazione, musicale]"
15,15,canale esaurire acqua alcuno parte costruzione...,migliore,7 marzo 2013,Tiffany H,2.0,"[canale, esaurire, acqua, alcuno, parte, costr...",[migliore]
23,23,museo maniera visita,noioso,8 agosto 2020,Irene antonacci,2.0,"[museo, maniera, visita]",[noioso]
88,88,zona aggiornare degrado diverso locale negozio...,caratteristico,6 novembre 2017,fyury,2.0,"[zona, aggiornare, degrado, diverso, locale, n...",[caratteristico]
113,113,troppo gente volere vedere piazza piazza capol...,,18 marzo 2019,Francesco,1.0,"[troppo, gente, volere, vedere, piazza, piazza...",[]
...,...,...,...,...,...,...,...,...
19506,19506,milanese generazione vedere sfruttamento quart...,tristissimo imitazione ambiente passato,18 maggio 2016,enmal m,2.0,"[milanese, generazione, vedere, sfruttamento, ...","[tristissimo, imitazione, ambiente, passato]"
19656,19656,locale carino moda perché potenziale,bello caratteristico,10 novembre 2011,Osvaldo D,2.0,"[locale, carino, moda, potenziale]",[caratteristico]
19727,19727,idea portare il turista sistemare argine passa...,delusione,19 agosto 2019,Elisa B,2.0,"[idea, portare, turista, sistemare, argine, pa...",[delusione]
19856,19856,delusione Berlino conoscere o voglia leggere i...,,10 gennaio 2017,coleus,2.0,"[delusione, berlino, conoscere, voglia, legger...",[]
19861,19861,vedere atmosfera mattina suscitare emozione po...,,8 settembre 2012,fosforo6,2.0,"[vedere, atmosfera, mattina, suscitare, emozio...",[]

In [256]:
titles_n=df_negative["title_preprocessed"].values
print(titles_n)
print(titles_n.shape)

[list(['gioco', 'acqua', 'natalizio', 'navigazione', 'musicale'])
 list(['migliore']) list(['noioso']) list(['caratteristico']) list([])
 list(['pensare']) list(['sporco']) list([]) list([]) list(['caos'])
 list(['organizzazione', 'inqualificabile']) list([])
 list(['simbolo', 'berlino']) list(['visita', 'guidare'])
 list(['godere', 'zona']) list(['turistico', 'interessante'])
 list(['museo', 'prado']) list(['vergogna', 'accessibilità'])
 list(['aspettare']) list(['migliorabile']) list(['sperare', 'expo'])
 list(['ridicolo']) list([]) list([]) list(['inconcepibile', 'pagare'])
 list(['pessimo', 'esperienza']) list(['museo', 'vecchio']) list([])
 list(['delusione']) list(['aspettare']) list(['relax'])
 list(['delusione']) list(['viaggio', 'madrid'])
 list(['navigli', 'mistero', 'targato', 'milano'])
 list(['navigare', 'percorso', 'darsena'])
 list(['servirebbe', 'modernità']) list(['reichstag']) list([])
 list(['adatto', 'bambino']) list(['servire', 'orario', 'prenotazione'])
 list(['delusione', 'totale']) list([]) list([])
 list(['ragazzino', 'area', 'accogliente']) list([])
 list(['iconico', 'maestoso', 'costoso']) list(['trascurare', 'sporco'])
 list([]) list(['piazza', 'duomo', 'periodo', 'natalizio'])
 list(['sopravvalutare']) list(['canale', 'veneziano'])
 list(['pieno', 'locale']) list(['limitato']) list(['complicare'])
 list(['opera', 'migliore', 'madrid'])
 list(['caratteristico', 'invivibile', 'sera', 'notte']) list([])
 list(['india']) list(['abbandonare', 'degrado', 'zona', 'storico'])
 list([]) list([]) list([]) list(['visita', 'azzoppato'])
 list(['occasione', 'perduto']) list([]) list(['microscopico']) list([])
 list(['nome', 'passare']) list([]) list([]) list(['banale'])
 list(['rumore', 'caos']) list(['caos']) list([])
 list(['organizzazione', 'cane']) list(['amare', 'milano']) list([])
 list([]) list(['splendido', 'occasione', 'gettato'])
 list(['confusionario', 'dispersivo']) list([]) list(['domanda'])
 list(['organizzato']) list(['carino'])
 list(['duomo', 'milano', 'meraviglioso'])
 list(['pessimo', 'organizzazione']) list(['meriterebbe'])
 list(['central', 'park']) list(['memorial', 'orrore']) list(['visita'])
 list(['tedesco']) list(['pensare']) list(['penoso']) list(['migliore'])
 list(['deluso']) list(['pagherò', 'chiesa']) list([])
 list(['atmosfera', 'natalizia']) list(['nascondere'])
 list(['fogna', 'cielo', 'aperto']) list([]) list(['sopravvalutare'])
 list(['evitabile']) list(['triste', 'squallido']) list(['dimenticare'])
 list(['cuore', 'interessante', 'vivace']) list([]) list(['venezia'])
 list(['pessimo']) list(['turista']) list(['rumore']) list([])
 list(['storia', 'berlino']) list(['delusione', 'totale'])
 list(['sensazione', 'particolare']) list(['mediocre'])
 list(['storia', 'bellezza', 'vanificare', 'eccesso', 'movida'])
 list(['abbandono']) list(['canale']) list(['mitico'])
 list(['paesaggio', 'intrigante', 'accogliente']) list([])
 list(['pomeriggio', 'deludente'])
 list(['pessimo', 'esperienza', 'trattare', 'derubare', 'cittadino', 'milano', 'turista'])
 list(['evitare']) list(['attesa', 'disattese'])
 list(['milano', 'monumento', 'chiuso', 'agosto'])
 list(['muro', 'posticcio']) list(['pessimo']) list(['deluso'])
 list(['noia', 'mortale']) list(['degrado', 'movida'])
 list(['opera', 'percorso']) list(['paradiso']) list(['significativo'])
 list(['pessimo', 'esperienza']) list(['zona', 'sopravvalutato'])
 list(['riflettere']) list(['capello', 'bianco'])
 list(['fama', 'sopravvalutato']) list(['schifo']) list([])
 list(['moglie']) list(['sì']) list(['visitare', 'cupola']) list([])
 list(['duomo']) list([]) list(['fare', 'attenzione'])
 list(['sorpresa', 'preavviso']) list(['navigli']) list(['impressione'])
 list(['migliorare']) list(['quartiere', 'trascurare', 'periferia'])
 list(['mancare', 'bagno']) list(['sfigato'])
 list(['simpatico', 'evitare']) list(['sopravvalutare']) list(['bah'])
 list([]) list(['arte', 'costare']) list(['pagare'])
 list(['dispersivo', 'opera', 'potere', 'interessare', 'persona', 'normale'])
 list(['insignificante']) list([]) list(['delusione']) list(['delusione'])
 list(['solito', 'organizzazione', 'italiano']) list(['devastazione'])
 list(['weekend', 'milanese']) list([]) list(['inutile'])
 list(['cena', 'disastroso'])
 list(['indirizzo', 'sbagliato', 'portare', 'opposto'])
 list(['visita', 'duomo']) list(['giro', 'battello', 'naviglio'])
 list(['ridicolo']) list(['saltare']) list(['delusione'])
 list(['memoriale']) list([]) list(['puzzolente', 'sporco', 'rumoroso'])
 list(['trascurare']) list(['disorganizzato', 'massimo'])
 list(['jog', 'usa']) list(['chiudere']) list(['stare']) list(['cupola'])
 list(['squallido', 'decadenza']) list(['rinunciare']) list(['aspettare'])
 list(['pessimo']) list(['delusione', 'totale'])
 list(['confusione', 'fare', 'arte'])
 list(['unico', 'museo', 'potere', 'foto']) list([])
 list(['colata', 'cemento']) list(['viaggio', 'istruzione'])
 list(['potere']) list(['odiare']) list(['pagare']) list([])
 list(['infamia', 'lode']) list(['biglietto', 'impalcatura']) list([])
 list(['confusionale']) list([]) list(['passeggiare', 'locale'])
 list(['esaltazione', 'nobile', 'spagnolo']) list(['canale', 'milano'])
 list(['aspettare']) list([]) list(['caotico'])
 list(['serata', 'compleanno']) list([]) list(['squallore', 'mostra'])
 list(['lasciare', 'stare']) list(['coda', 'sconsigliare'])
 list(['peggior', 'esperienza']) list(['mercatino', 'natale'])
 list(['strutturato']) list(['ascensore']) list(['culturale', 'caos'])
 list([]) list(['visitare', 'zona', 'canale', 'navigli'])
 list(['pessimo', 'organizzazione']) list(['curare'])
 list(['male', 'gestito']) list(['biglietto', 'guida']) list(['deludere'])
 list([]) list(['affascinare', 'impatto'])
 list(['organizzazione', 'chiarezza']) list(['noia', 'mortale'])
 list(['milano', 'scippare', 'autenticità'])
 list(['accozzaglia', 'opera', 'arte', 'percorso']) list([]) list([])
 list(['sopravvalutare']) list(['delusione']) list([])
 list(['consigliere']) list(['sportello', 'milano']) list([])
 list(['berlino']) list(['muro', 'berlino'])
 list(['chilometro', 'sbadiglio']) list(['deludere']) list(['chiudere'])
 list(['chiudere']) list(['gestire', 'duomo']) list(['inquinare'])
 list(['esperienza', 'negativo']) list(['colpire'])
 list(['visita', 'domenicale', 'museo', 'prado']) list(['delusione'])
 list(['trovare', 'particolare']) list([])
 list(['benvenuto', 'supermercato', 'alcatraz'])
 list(['memoriale', 'memorandum']) list(['domenica'])
 list(['esperienza', 'discreto', 'eccezionale']) list(['zona'])
 list(['controsenso']) list(['locale']) list(['duomo', 'milano']) list([])
 list(['personale']) list(['capisco']) list([]) list([])
 list(['navigli', 'vado', 'corrente', 'spiego'])
 list(['visita', 'cattedrale']) list([]) list(['funzionale', 'turista'])
 list(['tappa', 'obbligato']) list(['aspettare'])
 list(['gente', 'sporcizia']) list(['meraviglioso'])
 list(['fede', 'costo', 'vergogna'])
 list(['organizzazione', 'convincente'])
 list(['informazione', 'duomo', 'tecnologia']) list(['sponsor', 'soldo'])
 list(['pessimo', 'gestione', 'splendido', 'simbolo', 'milano'])
 list(['metà', 'duomo', 'chiuso', 'lavoro']) list([])
 list(['museo', 'sopravvalutato']) list(['tenere']) list([])
 list(['muro', 'mercé', 'capitalismo']) list(['scandaloso']) list([])
 list(['mah']) list(['carnaio', 'sopravvalutato']) list(['povero'])
 list(['cacciare', 'colpa', 'cappellino', 'inter']) list([])
 list(['acqua']) list(['delusione']) list(['evitare', 'peste'])
 list(['piacere'])
 list(['foro', 'corpo', 'dominare', 'cancro', 'graffito', 'muro'])
 list([]) list(['delusione']) list(['deludere']) list(['colpo', 'cuore'])
 list(['serata', 'febbraio']) list(['rivisitato']) list(['affollato'])
 list(['piacere']) list(['imbroglio']) list([])
 list(['pessina', 'esperienza']) list(['valorizzare']) list([])
 list(['eccezionale']) list(['tantissimo', 'gente', 'confusione'])
 list([]) list(['piacere']) list(['valore', 'pezzo', 'storia'])
 list(['migliore', 'bere', 'zanzara']) list([])
 list(['delusione', 'totale']) list(['rimanere', 'deluso'])
 list(['noioso']) list(['prenotazione']) list(['particolare'])
 list(['senso', 'unico']) list(['duomo', 'pagamento'])
 list(['centro', 'visita', 'sotterraneo', 'visita'])
 list(['navi', 'rovinare', 'movida']) list([])
 list(['giusto', 'passeggiata']) list(['boh'])
 list(['locale', 'resto', 'bah']) list(['tedioso', 'libro', 'storia'])
 list(['poliziotto']) list(['abbandono']) list(['sporco'])
 list(['speciale']) list(['valorizzare', 'tutelare'])
 list(['margine', 'miglioramento']) list(['personale', 'maleducato'])
 list(['tristissimo', 'imitazione', 'ambiente', 'passato'])
 list(['caratteristico']) list(['delusione']) list([]) list([])]
(348,)

In [257]:
print(titles_n[:5])

[list(['gioco', 'acqua', 'natalizio', 'navigazione', 'musicale'])
 list(['migliore']) list(['noioso']) list(['caratteristico']) list([])]

In [258]:
dictionary1=Dictionary(titles_n)
for token,id in dictionary1.token2id.items():
    print(f"{token}: {id}")

acqua: 0
gioco: 1
musicale: 2
natalizio: 3
navigazione: 4
migliore: 5
noioso: 6
caratteristico: 7
pensare: 8
sporco: 9
caos: 10
inqualificabile: 11
organizzazione: 12
berlino: 13
simbolo: 14
guidare: 15
visita: 16
godere: 17
zona: 18
interessante: 19
turistico: 20
museo: 21
prado: 22
accessibilità: 23
vergogna: 24
aspettare: 25
migliorabile: 26
expo: 27
sperare: 28
ridicolo: 29
inconcepibile: 30
pagare: 31
esperienza: 32
pessimo: 33
vecchio: 34
delusione: 35
relax: 36
madrid: 37
viaggio: 38
milano: 39
mistero: 40
navigli: 41
targato: 42
darsena: 43
navigare: 44
percorso: 45
modernità: 46
servirebbe: 47
reichstag: 48
adatto: 49
bambino: 50
orario: 51
prenotazione: 52
servire: 53
totale: 54
accogliente: 55
area: 56
ragazzino: 57
costoso: 58
iconico: 59
maestoso: 60
trascurare: 61
duomo: 62
periodo: 63
piazza: 64
sopravvalutare: 65
canale: 66
veneziano: 67
locale: 68
pieno: 69
limitato: 70
complicare: 71
opera: 72
invivibile: 73
notte: 74
sera: 75
india: 76
abbandonare: 77
degrado: 78
storico: 79
azzoppato: 80
occasione: 81
perduto: 82
microscopico: 83
nome: 84
passare: 85
banale: 86
rumore: 87
cane: 88
amare: 89
gettato: 90
splendido: 91
confusionario: 92
dispersivo: 93
domanda: 94
organizzato: 95
carino: 96
meraviglioso: 97
meriterebbe: 98
central: 99
park: 100
memorial: 101
orrore: 102
tedesco: 103
penoso: 104
deluso: 105
chiesa: 106
pagherò: 107
atmosfera: 108
natalizia: 109
nascondere: 110
aperto: 111
cielo: 112
fogna: 113
evitabile: 114
squallido: 115
triste: 116
dimenticare: 117
cuore: 118
vivace: 119
venezia: 120
turista: 121
storia: 122
particolare: 123
sensazione: 124
mediocre: 125
bellezza: 126
eccesso: 127
movida: 128
vanificare: 129
abbandono: 130
mitico: 131
intrigante: 132
paesaggio: 133
deludente: 134
pomeriggio: 135
cittadino: 136
derubare: 137
trattare: 138
evitare: 139
attesa: 140
disattese: 141
agosto: 142
chiuso: 143
monumento: 144
muro: 145
posticcio: 146
mortale: 147
noia: 148
paradiso: 149
significativo: 150
sopravvalutato: 151
riflettere: 152
bianco: 153
capello: 154
fama: 155
schifo: 156
moglie: 157
sì: 158
cupola: 159
visitare: 160
attenzione: 161
fare: 162
preavviso: 163
sorpresa: 164
impressione: 165
migliorare: 166
periferia: 167
quartiere: 168
bagno: 169
mancare: 170
sfigato: 171
simpatico: 172
bah: 173
arte: 174
costare: 175
interessare: 176
normale: 177
persona: 178
potere: 179
insignificante: 180
italiano: 181
solito: 182
devastazione: 183
milanese: 184
weekend: 185
inutile: 186
cena: 187
disastroso: 188
indirizzo: 189
opposto: 190
portare: 191
sbagliato: 192
battello: 193
giro: 194
naviglio: 195
saltare: 196
memoriale: 197
puzzolente: 198
rumoroso: 199
disorganizzato: 200
massimo: 201
jog: 202
usa: 203
chiudere: 204
stare: 205
decadenza: 206
rinunciare: 207
confusione: 208
foto: 209
unico: 210
cemento: 211
colata: 212
istruzione: 213
odiare: 214
infamia: 215
lode: 216
biglietto: 217
impalcatura: 218
confusionale: 219
passeggiare: 220
esaltazione: 221
nobile: 222
spagnolo: 223
caotico: 224
compleanno: 225
serata: 226
mostra: 227
squallore: 228
lasciare: 229
coda: 230
sconsigliare: 231
peggior: 232
mercatino: 233
natale: 234
strutturato: 235
ascensore: 236
culturale: 237
curare: 238
gestito: 239
male: 240
guida: 241
deludere: 242
affascinare: 243
impatto: 244
chiarezza: 245
autenticità: 246
scippare: 247
accozzaglia: 248
consigliere: 249
sportello: 250
chilometro: 251
sbadiglio: 252
gestire: 253
inquinare: 254
negativo: 255
colpire: 256
domenicale: 257
trovare: 258
alcatraz: 259
benvenuto: 260
supermercato: 261
memorandum: 262
domenica: 263
discreto: 264
eccezionale: 265
controsenso: 266
personale: 267
capisco: 268
corrente: 269
spiego: 270
vado: 271
cattedrale: 272
funzionale: 273
obbligato: 274
tappa: 275
gente: 276
sporcizia: 277
costo: 278
fede: 279
convincente: 280
informazione: 281
tecnologia: 282
soldo: 283
sponsor: 284
gestione: 285
lavoro: 286
metà: 287
tenere: 288
capitalismo: 289
mercé: 290
scandaloso: 291
mah: 292
carnaio: 293
povero: 294
cacciare: 295
cappellino: 296
colpa: 297
inter: 298
peste: 299
piacere: 300
cancro: 301
corpo: 302
dominare: 303
foro: 304
graffito: 305
colpo: 306
febbraio: 307
rivisitato: 308
affollato: 309
imbroglio: 310
pessina: 311
valorizzare: 312
tantissimo: 313
pezzo: 314
valore: 315
bere: 316
zanzara: 317
rimanere: 318
senso: 319
pagamento: 320
centro: 321
sotterraneo: 322
navi: 323
rovinare: 324
giusto: 325
passeggiata: 326
boh: 327
resto: 328
libro: 329
tedioso: 330
poliziotto: 331
speciale: 332
tutelare: 333
margine: 334
miglioramento: 335
maleducato: 336
ambiente: 337
imitazione: 338
passato: 339
tristissimo: 340

In [275]:
#dictionary1.filter_extremes(no_above=120, keep_n=300)----> salto questo passaggio altrimenti rimangono troppe poche features

In [260]:
X4=[dictionary1.doc2bow(title) for title in titles_n]
print("Ecco i primi tre titoli in formato bow (indice,numero di occorrenze)\n ")
print(X4[:3])

Ecco i primi tre titoli in formato bow (indice,numero di occorrenze)

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1)], [(5, 1)], [(6, 1)]]

In [261]:
lda_gensim_n=LdaMulticore(X4, num_topics=3,id2word=dictionary1,passes=250,workers=3)
#1 minuto

In [262]:
for index, topic in lda_gensim_n.print_topics():
    print("\nTOPIC %d - parole più popolari" %(index+1))
    print(topic)

TOPIC 1 - parole più popolari
0.030*"milano" + 0.027*"pessimo" + 0.027*"duomo" + 0.024*"visita" + 0.021*"esperienza" + 0.021*"organizzazione" + 0.015*"museo" + 0.013*"opera" + 0.013*"migliore" + 0.013*"locale"

TOPIC 2 - parole più popolari
0.018*"sporco" + 0.014*"zona" + 0.014*"chiudere" + 0.014*"deludere" + 0.010*"mortale" + 0.010*"noia" + 0.010*"viaggio" + 0.010*"degrado" + 0.010*"valorizzare" + 0.010*"pensare"

TOPIC 3 - parole più popolari
0.052*"delusione" + 0.019*"aspettare" + 0.016*"totale" + 0.016*"caos" + 0.016*"sopravvalutare" + 0.016*"berlino" + 0.016*"sopravvalutato" + 0.016*"canale" + 0.016*"muro" + 0.012*"particolare"

In [263]:
lda_gensim_n_vis=pyLDAvis.gensim.prepare(lda_gensim_n,X4 ,dictionary1, mds='tsne')
pyLDAvis.display(lda_gensim_n_vis)

* All' interno delle parole chiave selezionate nei vari topic, se ne cominciano a vedere alcune che fanno riferimento a quli sono stati gli aspetti negativi riscontrati : caos, sporcizia, attesa, (dis)organizzazione. Queste parole sono però mischiate nei 3 topic e quindi non permettono di associare ciascun topic ad una specifica categoria di aspetti negativi. Lo stesso vale per il caso delle recensioni positive

# Conclusione

*  A conclusione del lavoro ripetiamo gli stessi passaggi dell'algoritmo di topic extraction con la libreria Gensim, utilizzando nuovamente l'intero corpus formato da tutti i commenti prodotti dagli utenti.
* Utilizziamo questa volta la codifica Tf-Idf

In [264]:
df["comment"]=corpus_cleam
df["comment_preprocessed"]=df["comment"].map(preprocess)
df.head(20)

,Unnamed: 0,comment,title,date,name,stars,comment_preprocessed
0,0,interessante sera trambusto età sacco bar rist...,Zona del canal grande,26 ottobre 2016,gfdmmad,5.0,"[interessante, sera, trambusto, età, sacco, ba..."
1,1,organizzare coda entrata piantine visita perco...,Visita di piacere,26 aprile 2019,Diabolik-Eva-014,5.0,"[organizzare, coda, entrata, piantine, visita,..."
2,2,amico o expo strada il navigli porto darsena r...,Da vedere a Milano,18 novembre 2018,O5262KGchrisd,5.0,"[amico, expo, strada, navigli, porto, darsena,..."
3,3,visitare duomo Milano madonnina guglia esperie...,Il Duomo sempre affascinante,7 agosto 2019,Babellina,5.0,"[visitare, duomo, milano, madonnina, guglia, e..."
4,4,vista duomo uscita metro togliere fiato il lav...,Eccezionale,9 dicembre 2019,Nik804,5.0,"[vista, duomo, uscita, metro, togliere, fiato,..."
5,5,Milano visitare chiesa cuore Milano passo univ...,Visita imperdibile!,21 aprile 2017,matteodifelice,5.0,"[milano, visitare, chiesa, cuore, milano, pass..."
6,6,tenere passeggiare stare,Un oasi nel caos,23 dicembre 2017,Ghert2015,4.0,"[tenere, passeggiare, stare]"
7,7,creare traccia passato impedire adeguare si es...,La Bernauerstrasse sospesa tra passato e presente,10 febbraio 2017,bobmonica,5.0,"[creare, traccia, passato, impedire, adeguare,..."
8,8,parola descrivere bellezza parco passeggiare c...,Imperdibile,6 novembre 2016,Duecuorieunaciccions,5.0,"[parola, descrivere, bellezza, parco, passeggi..."
9,9,polmone simbolo New York consigliare passeggia...,Passeggiata obbligatoria,23 novembre 2017,CDam7,5.0,"[polmone, simbolo, new, york, consigliare, pas..."
10,10,visitare milano periodo Natale mille rendere p...,Giochi d'acqua natalizi e navigazione musicale,15 dicembre 2019,Alessandra d,1.0,"[visitare, milano, periodo, natale, mille, ren..."
11,11,stagione girare prendere barchetta rema laghet...,Domenica al parco,7 ottobre 2017,Elisabetta P,5.0,"[stagione, girare, prendere, barchetta, rema, ..."
12,12,attrazione vedere ingresso audio guida edifici...,visita a berlino,17 marzo 2019,V586OIdavide,4.0,"[attrazione, ingresso, audio, guida, edificio,..."
13,13,arrivare cogliere desolazione memoriale cammin...,Lo smarrimento della ragione,5 aprile 2019,Aurora P,4.0,"[arrivare, cogliere, desolazione, memoriale, c..."
14,14,il sale frescura picnic leggere il bimbo anzia...,il parco dei desideri,6 febbraio 2017,Saverio Ammendola,5.0,"[sale, frescura, picnic, leggere, bimbo, anzia..."
15,15,canale esaurire acqua alcuno parte costruzione...,Non è il migliore,7 marzo 2013,Tiffany H,2.0,"[canale, esaurire, acqua, alcuno, parte, costr..."
16,16,caravaggio Velasquez raffaello rene goya amant...,"È bellissimo, gratis dalle 18 alle 20",30 settembre 2018,viaggiatorelowcost,5.0,"[caravaggio, velasquez, raffaello, rene, goya,..."
17,17,zona Milano visitare trovandola sera vedere porta,Rilassante,25 gennaio 2016,Nocciolino72,3.0,"[zona, milano, visitare, trovandola, sera, porta]"
18,18,parco trovare spazio impegnare noleggiare gira...,Relax e sport!,14 agosto 2017,Fram05,5.0,"[parco, trovare, spazio, impegnare, noleggiare..."
19,19,il giro poco locale moda orario cè troppo conf...,I navigli...,23 settembre 2018,Vincenzo,3.0,"[giro, locale, moda, orario, cè, confusione, c..."

In [265]:
complete_corpus=df["comment_preprocessed"].values
print(complete_corpus)
print(complete_corpus.shape)

[list(['interessante', 'sera', 'trambusto', 'età', 'sacco', 'bar', 'ristorante', 'canal', 'street', 'negozio', 'prezzo', 'rimanere', 'soddisfatto', 'mangiare', 'zoccolo', 'portato', 'notte', 'sembrare', 'visitare', 'volere', 'perdere', 'trovare', 'milano'])
 list(['organizzare', 'coda', 'entrata', 'piantine', 'visita', 'percorso', 'controllo'])
 list(['amico', 'expo', 'strada', 'navigli', 'porto', 'darsena', 'ristrutturare', 'gioiello', 'atmosfera', 'centro', 'casa', 'negozio', 'decina', 'bar', 'ristorante', 'posizione', 'shop', 'rilassare'])
 ...
 list(['mancare', 'beato', 'mantegna', 'tiziano', 'raffaello', 'velazquez', 'goya', 'bosch', 'preferito', 'assoluto', 'fruizione', 'museo', 'permettere', 'visita'])
 list(['porta', 'simbolo', 'quadriga', 'sormonta', 'venire', 'trafugare', 'napoleone', 'bottino', 'guerra'])
 list(['darsena', 'biforcazione', 'ripristinare', 'restyling', 'fantastica', 'atmosfera', 'serata', 'locale', 'camminata', 'adiacente', 'acqua', 'fantasticare', 'frequentare'])]
(20058,)

In [266]:
print(complete_corpus[:5])

[list(['interessante', 'sera', 'trambusto', 'età', 'sacco', 'bar', 'ristorante', 'canal', 'street', 'negozio', 'prezzo', 'rimanere', 'soddisfatto', 'mangiare', 'zoccolo', 'portato', 'notte', 'sembrare', 'visitare', 'volere', 'perdere', 'trovare', 'milano'])
 list(['organizzare', 'coda', 'entrata', 'piantine', 'visita', 'percorso', 'controllo'])
 list(['amico', 'expo', 'strada', 'navigli', 'porto', 'darsena', 'ristrutturare', 'gioiello', 'atmosfera', 'centro', 'casa', 'negozio', 'decina', 'bar', 'ristorante', 'posizione', 'shop', 'rilassare'])
 list(['visitare', 'duomo', 'milano', 'madonnina', 'guglia', 'esperienza', 'vivere'])
 list(['vista', 'duomo', 'uscita', 'metro', 'togliere', 'fiato', 'lavoro', 'interno', 'tralasciare'])]

In [267]:
dictionary2=Dictionary(complete_corpus)
for token,id in dictionary2.token2id.items():
    print(f"{token}: {id}")

bar: 0
canal: 1
età: 2
interessante: 3
mangiare: 4
milano: 5
negozio: 6
notte: 7
perdere: 8
portato: 9
prezzo: 10
rimanere: 11
ristorante: 12
sacco: 13
sembrare: 14
sera: 15
soddisfatto: 16
street: 17
trambusto: 18
trovare: 19
visitare: 20
volere: 21
zoccolo: 22
coda: 23
controllo: 24
entrata: 25
organizzare: 26
percorso: 27
piantine: 28
visita: 29
amico: 30
atmosfera: 31
casa: 32
centro: 33
darsena: 34
decina: 35
expo: 36
gioiello: 37
navigli: 38
porto: 39
posizione: 40
rilassare: 41
ristrutturare: 42
shop: 43
strada: 44
duomo: 45
esperienza: 46
guglia: 47
madonnina: 48
vivere: 49
fiato: 50
interno: 51
lavoro: 52
metro: 53
togliere: 54
tralasciare: 55
uscita: 56
vista: 57
affresco: 58
aspettativa: 59
bellezza: 60
chiesa: 61
cuore: 62
intento: 63
passo: 64
riuscire: 65
superare: 66
università: 67
passeggiare: 68
stare: 69
tenere: 70
adeguare: 71
creare: 72
esigenza: 73
impedire: 74
passato: 75
sito: 76
terrazzo: 77
traccia: 78
affittare: 79
colore: 80
descrivere: 81
film: 82
follia: 83
mezzo: 84
parco: 85
parola: 86
perimetro: 87
sentire: 88
star: 89
tornare: 90
valsa: 91
attività: 92
consigliare: 93
new: 94
passeggiata: 95
polmone: 96
simbolo: 97
york: 98
accesso: 99
accompagnare: 100
acqua: 101
acquisto: 102
arancio: 103
artista: 104
assistere: 105
azzurro: 106
bianco: 107
biglietto: 108
chiosco: 109
coro: 110
danzare: 111
desiderare: 112
dicembre: 113
drink: 114
evento: 115
fontana: 116
food: 117
loco: 118
mille: 119
musica: 120
natale: 121
navigazione: 122
novembre: 123
partecipazione: 124
passare: 125
periodo: 126
pianista: 127
pu: 128
rendere: 129
ritmo: 130
spettacolo: 131
tono: 132
albero: 133
barchetta: 134
girare: 135
laghetto: 136
ombra: 137
prato: 138
prendere: 139
rema: 140
ristorantino: 141
stagione: 142
acciaio: 143
attrazione: 144
audio: 145
carattere: 146
cupola: 147
edificio: 148
guida: 149
ingresso: 150
piano: 151
possibilità: 152
rampa: 153
suggestivo: 154
superba: 155
vetro: 156
arrivare: 157
blocco: 158
camminare: 159
capire: 160
cemento: 161
cogliere: 162
coscienza: 163
desolazione: 164
foto: 165
idiozia: 166
memoriale: 167
perdita: 168
posa: 169
raccoglimento: 170
scattare: 171
smarrimento: 172
spiaggia: 173
terrore: 174
turista: 175
umanità: 176
anziano: 177
bimbo: 178
frescura: 179
leggere: 180
oasi: 181
picnic: 182
sale: 183
sorvegliare: 184
acquistare: 185
alcuno: 186
aspettare: 187
bevanda: 188
birra: 189
bottiglia: 190
canale: 191
comprendere: 192
conoscenza: 193
costruzione: 194
elemento: 195
esaurire: 196
finire: 197
mercato: 198
parte: 199
pulce: 200
self: 201
stick: 202
sudore: 203
telefono: 204
terra: 205
tipo: 206
zona: 207
amante: 208
arte: 209
caravaggio: 210
fila: 211
goya: 212
raffaello: 213
rene: 214
velasquez: 215
porta: 216
trovandola: 217
area: 218
gioco: 219
impegnare: 220
manhattan: 221
noleggiare: 222
passaggio: 223
spazio: 224
staccare: 225
trovi: 226
confusione: 227
cè: 228
giro: 229
locale: 230
moda: 231
orario: 232
accogliere: 233
cittadino: 234
credere: 235
divertimento: 236
ny: 237
primis: 238
scoiattolo: 239
speranza: 240
cappella: 241
esterno: 242
gioia: 243
merito: 244
paragono: 245
soglia: 246
varcare: 247
visitatore: 248
volontario: 249
andare: 250
aperitivo: 251
buttare: 252
parlare: 253
particolare: 254
pensare: 255
soldo: 256
voglia: 257
maniera: 258
museo: 259
bambino: 260
carrozza: 261
cavallo: 262
cocchiere: 263
fare: 264
oretta: 265
posto: 266
sedere: 267
tirare: 268
central: 269
nevicare: 270
park: 271
persona: 272
piacere: 273
animale: 274
fortuna: 275
giornata: 276
incanto: 277
incontrare: 278
inverno: 279
portare: 280
ricerca: 281
scaldare: 282
seguire: 283
sentiero: 284
sole: 285
barca: 286
bethesda: 287
fountain: 288
lontano: 289
nic: 290
pattinaggio: 291
pic: 292
pista: 293
potere: 294
risciò: 295
dovere: 296
preferire: 297
cielo: 298
fascino: 299
curare: 300
giardino: 301
punto: 302
soddisfare: 303
amare: 304
riservare: 305
ritornare: 306
mostrare: 307
prenotazione: 308
genere: 309
accedere: 310
aula: 311
aurelio: 312
autore: 313
bernardino: 314
cappe: 315
caratterizzare: 316
celare: 317
club: 318
corso: 319
disposizione: 320
diverso: 321
dividere: 322
divisorio: 323
facciata: 324
fedele: 325
fianco: 326
figlio: 327
giovan: 328
indicare: 329
luino: 330
meraviglia: 331
monaca: 332
navata: 333
nonché: 334
organo: 335
parete: 336
pietro: 337
resto: 338
riempie: 339
scoprire: 340
sguardo: 341
sistina: 342
tour: 343
venire: 344
via: 345
accorgere: 346
opera: 347
sosta: 348
terminare: 349
trascorrere: 350
frequentare: 351
gente: 352
ideale: 353
pavimentazione: 354
promuovere: 355
tacco: 356
autunno: 357
paradiso: 358
approfondire: 359
cinque: 360
dimensione: 361
gestire: 362
ingannare: 363
lasciare: 364
meritare: 365
meriterebbero: 366
quinto: 367
regalare: 368
sala: 369
sorpresa: 370
stella: 371
virtù: 372
ammirare: 373
chiave: 374
conoscere: 375
disponibilità: 376
panorama: 377
recupero: 378
richiesta: 379
sistema: 380
terrazza: 381
alcolico: 382
individuo: 383
pulire: 384
relax: 385
verde: 386
art: 387
freedom: 388
libertà: 389
more: 390
murales: 391
pace: 392
bicicletta: 393
evitare: 394
fiore: 395
jog: 396
moglie: 397
noleggio: 398
pianta: 399
primavera: 400
stupende: 401
sud: 402
tappa: 403
anagrafe: 404
aperto: 405
cena: 406
colpa: 407
coppia: 408
cucina: 409
difficoltà: 410
effetto: 411
entusiasmo: 412
giovane: 413
ispirare: 414
location: 415
soffro: 416
dedicare: 417
cerco: 418
naviglio: 419
vado: 420
caldo: 421
estate: 422
neve: 423
perdo: 424
qualsiasi: 425
by: 426
fermare: 427
monumento: 428
night: 429
altro: 430
esso: 431
gradire: 432
guidare: 433
italiano: 434
proseguire: 435
assaporare: 436
cultura: 437
meneghino: 438
nascondere: 439
occhio: 440
abitante: 441
auto: 442
caos: 443
grattacielo: 444
nn: 445
paio: 446
rigenerare: 447
den: 448
divisione: 449
germania: 450
linden: 451
unità: 452
unter: 453
viale: 454
avviso: 455
berlino: 456
cambiamento: 457
complessità: 458
conoscente: 459
maurizio: 460
san: 461
emozione: 462
innamorare: 463
prado: 464
tantissima: 465
bici: 466
direzione: 467
passeggino: 468
vacanza: 469
altare: 470
osservare: 471
raggiungere: 472
senso: 473
divenire: 474
movida: 475
modifica: 476
stupire: 477
circondare: 478
impressione: 479
natura: 480
apprezzare: 481
mancare: 482
parente: 483
respirare: 484
torno: 485
bice: 486
bistrot: 487
donuts: 488
lato: 489
prodotto: 490
commentare: 491
maestoso: 492
piazza: 493
fretta: 494
riposare: 495
abituare: 496
chilometro: 497
navigare: 498
pensavamo: 499
roma: 500
sorpassare: 501
diventare: 502
emozionare: 503
personale: 504
tramonto: 505
problema: 506
risolvere: 507
salone: 508
sensazione: 509
carta: 510
chiedere: 511
guerra: 512
malfattore: 513
muro: 514
nota: 515
percorrere: 516
spillare: 517
stazione: 518
attirare: 519
continuo: 520
dimenticare: 521
intitolare: 522
nome: 523
santo: 524
statua: 525
aeroporto: 526
amorino: 527
arrosto: 528
centrale: 529
gelato: 530
limone: 531
pangrattato: 532
patate: 533
pausa: 534
piatto: 535
riempire: 536
rientrare: 537
rosolare: 538
trattoria: 539
vitello: 540
addict: 541
clima: 542
mattina: 543
orde: 544
settimana: 545
thanksgiving: 546
angolo: 547
cammino: 548
corro: 549
curiosare: 550
erba: 551
essere: 552
panchina: 553
scopro: 554
targa: 555
struttura: 556
contesto: 557
correre: 558
immersi: 559
aperti: 560
apertura: 561
aprire: 562
avvenire: 563
causare: 564
complesso: 565
determinato: 566
domenica: 567
fase: 568
leggo: 569
luglio: 570
martedì: 571
motivo: 572
partire: 573
recensione: 574
restauro: 575
ricordare: 576
scrivere: 577
sicurezza: 578
antonio: 579
arca: 580
attribuire: 581
bergognone: 582
campo: 583
cappello: 584
definire: 585
maestro: 586
monastero: 587
mq: 588
presentare: 589
realizzare: 590
scuola: 591
simone: 592
storia: 593
ciò: 594
provenire: 595
pubblico: 596
restare: 597
tci: 598
aspetto: 599
attesa: 600
biglietteria: 601
cattedrale: 602
idea: 603
metà: 604
permettere: 605
provvedere: 606
ritrovare: 607
servire: 608
servizio: 609
sportello: 610
tetto: 611
base: 612
bere: 613
causa: 614
happy: 615
hour: 616
quantità: 617
sfilza: 618
zanzara: 619
appassionato: 620
itinerario: 621
madrid: 622
saluto: 623
veduta: 624
quartiere: 625
abitare: 626
dare: 627
frenesia: 628
grigio: 629
lago: 630
meta: 631
movimento: 632
palazzo: 633
pino: 634
quadro: 635
riflesso: 636
spezzare: 637
uccello: 638
celebrare: 639
chiudere: 640
clausura: 641
decorare: 642
lunedì: 643
mantenere: 644
soffitto: 645
suddividere: 646
suora: 647
svolgere: 648
arteria: 649
bastare: 650
chiusa: 651
cosa: 652
elogiare: 653
fiere: 654
guardare: 655
immobile: 656
insistere: 657
intervallo: 658
invenzione: 659
invidiare: 660
leonardo: 661
lista: 662
martesana: 663
milanese: 664
pavese: 665
pianeta: 666
portello: 667
ricoprire: 668
son: 669
sponda: 670
svariato: 671
tornerebbe: 672
viandante: 673
vicinanza: 674
aggiornare: 675
degrado: 676
ospitare: 677
alzare: 678
city: 679
corsetta: 680
giocherellare: 681
mattino: 682
ponte: 683
offrire: 684
stancante: 685
adorare: 686
bosco: 687
organizzazione: 688
approcciare: 689
scegliere: 690
temperatura: 691
trattare: 692
foglia: 693
proprio: 694
prenotare: 695
praticare: 696
ristorazione: 697
sport: 698
galleria: 699
godere: 700
architettura: 701
occasione: 702
ambiente: 703
concerto: 704
diluvio: 705
grata: 706
illustrare: 707
prestare: 708
scena: 709
usare: 710
parto: 711
rettangolo: 712
cerca: 713
offerta: 714
ricco: 715
wow: 716
popolo: 717
gustare: 718
luogo: 719
coprire: 720
manifestazione: 721
stand: 722
valore: 723
mercatino: 724
oggetto: 725
riscoprire: 726
boccata: 727
ossigeno: 728
capolavoro: 729
affluenza: 730
assoluto: 731
el: 732
fregola: 733
goduta: 734
necessitare: 735
pazienza: 736
pretendere: 737
rubens: 738
sconsiglio: 739
spesa: 740
coinvolgere: 741
tratto: 742
milan: 743
startup: 744
ammettere: 745
iniziare: 746
lira: 747
reazione: 748
sapere: 749
ta: 750
meravigliare: 751
trasformare: 752
eccellenza: 753
salito: 754
consuete: 755
indicazione: 756
spiegazione: 757
vorrebbero: 758
brandeburgo: 759
cartolina: 760
comprensione: 761
east: 762
gratuito: 763
inglese: 764
pannello: 765
sabato: 766
stupidi: 767
aria: 768
paesaggio: 769
conformazione: 770
fantasticare: 771
provare: 772
yay: 773
delusa: 774
realtà: 775
refrigerio: 776
febbraio: 777
imprimere: 778
mente: 779
ragazza: 780
collection: 781
corsia: 782
ritirare: 783
ticket: 784
trasportare: 785
costo: 786
distendere: 787
gabbiotto: 788
ripresa: 789
citare: 790
metropoli: 791
fama: 792
francia: 793
livello: 794
louvre: 795
parere: 796
paura: 797
sofia: 798
supremazia: 799
uffizio: 800
imponente: 801
miniatura: 802
salto: 803
culturale: 804
decidere: 805
marito: 806
pomeriggio: 807
bisogno: 808
borsa: 809
gentaccia: 810
mirare: 811
immersione: 812
migliaio: 813
sogno: 814
calma: 815
complicato: 816
chiusura: 817
limitare: 818
sfruttare: 819
velazquez: 820
viaggio: 821
colpire: 822
spaesamento: 823
trasmettere: 824
larghezza: 825
controllare: 826
iniziativa: 827
mettere: 828
bancarella: 829
ascoltare: 830
ce: 831
center: 832
dato: 833
documentation: 834
documento: 835
epoca: 836
fornire: 837
giornale: 838
impatto: 839
piangere: 840
raccogliere: 841
siam: 842
straße: 843
testimonianza: 844
vita: 845
blogger: 846
consigliere: 847
fashion: 848
gallery: 849
graffito: 850
gusto: 851
sfondo: 852
side: 853
stile: 854
trovo: 855
utilizzare: 856
ascesa: 857
ebreo: 858
mostra: 859
oppositore: 860
raccontare: 861
regime: 862
sottoporre: 863
uso: 864
vessazione: 865
adozione: 866
vivo: 867
caffè: 868
dettaglio: 869
pulizia: 870
contorno: 871
londra: 872
scenario: 873
vegetazione: 874
corsa: 875
esistere: 876
esplosione: 877
fauna: 878
flora: 879
accorciare: 880
bosch: 881
esposizione: 882
line: 883
on: 884
tempo: 885
temporanee: 886
appassionare: 887
armare: 888
capacità: 889
collaudare: 890
lasceremo: 891
libro: 892
mappa: 893
orientamento: 894
premesso: 895
prevedere: 896
puntare: 897
rischiare: 898
vietare: 899
appuntamento: 900
convento: 901
intense: 902
ordine: 903
ospedale: 904
ritenere: 905
sede: 906
assenza: 907
biga: 908
chiamare: 909
scommessa: 910
sorgere: 911
visitano: 912
fregatura: 913
parlamento: 914
est: 915
giretto: 916
meet: 917
mela: 918
museum: 919
of: 920
ovest: 921
prendetevi: 922
affascinare: 923
dire: 924
salire: 925
animaletto: 926
atmosfere: 927
incrocio: 928
tocco: 929
pagare: 930
battistero: 931
contrario: 932
folla: 933
obolo: 934
pasqua: 935
scarsezza: 936
baseball: 937
coperta: 938
cornice: 939
costeggiare: 940
onassis: 941
tennis: 942
carrozzella: 943
ghiaccio: 944
pattinare: 945
pranzare: 946
spettacolare: 947
spiegare: 948
mattinata: 949
must: 950
ascensore: 951
euro: 952
marmo: 953
pagamento: 954
saltare: 955
scala: 956
allestimento: 957
dramma: 958
perchè: 959
separazione: 960
significato: 961
sorprendere: 962
tagliare: 963
italia: 964
cenacolo: 965
cerimonia: 966
decisione: 967
destinare: 968
dipinto: 969
maria: 970
passione: 971
privare: 972
restituire: 973
santa: 974
sinistra: 975
sì: 976
unire: 977
varietà: 978
barra: 979
check: 980
out: 981
trattativa: 982
ambiguo: 983
favola: 984
foresta: 985
grado: 986
personaggio: 987
punta: 988
ridire: 989
avvenimento: 990
descrizione: 991
giunta: 992
persecuzione: 993
annoiare: 994
intere: 995
interesse: 996
john: 997
lennon: 998
poiché: 999
preferito: 1000
riportare: 1001
risultare: 1002
sofferenza: 1003
solitudine: 1004
accordo: 1005
brera: 1006
calcio: 1007
concentrato: 1008
fascia: 1009
modificare: 1010
riunire: 1011
scorcio: 1012
siro: 1013
scontare: 1014
durare: 1015
stanza: 1016
obbligo: 1017
respiro: 1018
ricordo: 1019
rievocare: 1020
sollievo: 1021
tiro: 1022
articolo: 1023
rispetto: 1024
silenzio: 1025
bela: 1026
fondere: 1027
sentimento: 1028
capitare: 1029
comprare: 1030
contenuto: 1031
video: 1032
gioiellino: 1033
insolito: 1034
piantare: 1035
quadrare: 1036
tesoro: 1037
dispersivo: 1038
ambientare: 1039
belvedere: 1040
castello: 1041
castle: 1042
cottage: 1043
marionette: 1044
meteo: 1045
piú: 1046
puffo: 1047
rilevare: 1048
score: 1049
teatro: 1050
doppiare: 1051
mezzogiorno: 1052
popolare: 1053
tripudio: 1054
colmo: 1055
an: 1056
disposto: 1057
distruggere: 1058
eucarestia: 1059
invogliare: 1060
messa: 1061
officiare: 1062
porre: 1063
ricevere: 1064
approfittatene: 1065
costare: 1066
hudson: 1067
largo: 1068
muovere: 1069
andere: 1070
ripetere: 1071
rischio: 1072
pittore: 1073
riferimento: 1074
filo: 1075
anima: 1076
condizione: 1077
corpo: 1078
divagare: 1079
cocktail: 1080
compagnia: 1081
pizzeria: 1082
pub: 1083
serata: 1084
sigaretta: 1085
trasferire: 1086
deceduto: 1087
labirinto: 1088
olocausto: 1089
pittura: 1090
refettorio: 1091
addobbi: 1092
luce: 1093
abbandonare: 1094
progetto: 1095
rinnovamento: 1096
risorsa: 1097
sperare: 1098
squallore: 1099
uscire: 1100
distrazione: 1101
famiglia: 1102
tranquillità: 1103
zoo: 1104
consumare: 1105
scarpa: 1106
telo: 1107
accadere: 1108
elaborare: 1109
segno: 1110
conto: 1111
evidenza: 1112
giocare: 1113
bocca: 1114
brivido: 1115
effettuare: 1116
pensiero: 1117
vittima: 1118
giungla: 1119
isola: 1120
unico: 1121
clacson: 1122
dog: 1123
fatelo: 1124
godetevi: 1125
hot: 1126
meritato: 1127
recinzione: 1128
rumore: 1129
stendere: 1130
traffico: 1131
beach: 1132
immergersi: 1133
notorietà: 1134
particolarità: 1135
stress: 1136
capatina: 1137
addobbare: 1138
alpine: 1139
gestapo: 1140
polizia: 1141
quartier: 1142
affollato: 1143
amore: 1144
serratura: 1145
decorazione: 1146
immaginare: 1147
ricoprono: 1148
separare: 1149
sola: 1150
stucco: 1151
tramezzo: 1152
esplorare: 1153
bronzo: 1154
scultura: 1155
fidanzato: 1156
giù: 1157
nostalgia: 1158
roccia: 1159
classico: 1160
imparare: 1161
pelle: 1162
pezzo: 1163
disporre: 1164
fiammingo: 1165
importanza: 1166
valere: 1167
divertire: 1168
ragazzo: 1169
raoul: 1170
simpatia: 1171
impressionato: 1172
fan: 1173
field: 1174
freddo: 1175
memorial: 1176
installazione: 1177
colonna: 1178
selezionare: 1179
soluzione: 1180
diamante: 1181
skyline: 1182
attraversare: 1183
lungo: 1184
metropolitana: 1185
nazione: 1186
core: 1187
giallo: 1188
maratona: 1189
sfumatura: 1190
affitto: 1191
colorare: 1192
entro: 1193
vetrata: 1194
cortina: 1195
documentazione: 1196
ferro: 1197
memoria: 1198
obbligare: 1199
racchiudere: 1200
rappresentare: 1201
tubo: 1202
venezia: 1203
approfondimento: 1204
condizionare: 1205
consentire: 1206
documentare: 1207
orrore: 1208
rovinare: 1209
deambulazione: 1210
aereo: 1211
mamma: 1212
passeggio: 1213
cenare: 1214
esistenza: 1215
ignorare: 1216
soffermare: 1217
trittico: 1218
internet: 1219
presenza: 1220
apartments: 1221
ere: 1222
gemelle: 1223
nyc: 1224
torri: 1225
fotografare: 1226
apericena: 1227
appassionata: 1228
chiacchierare: 1229
considero: 1230
donna: 1231
etnico: 1232
lavandaia: 1233
marea: 1234
memorabile: 1235
odore: 1236
panno: 1237
patria: 1238
pietra: 1239
tavolo: 1240
vicolo: 1241
maestosità: 1242
rendi: 1243
attenzione: 1244
vialetto: 1245
collocazione: 1246
intendere: 1247
merita: 1248
pecca: 1249
pò: 1250
atelier: 1251
notare: 1252
vai: 1253
abitazione: 1254
altezza: 1255
beatles: 1256
canoa: 1257
cantante: 1258
frenetica: 1259
grandezza: 1260
mosaico: 1261
permanenza: 1262
rincorrere: 1263
west: 1264
linea: 1265
pulito: 1266
accendere: 1267
fatica: 1268
avvicinare: 1269
cibo: 1270
giugno: 1271
immergere: 1272
pisolino: 1273
schiacciare: 1274
sdraiare: 1275
serenità: 1276
splendido: 1277
cercare: 1278
intervento: 1279
passerebbe: 1280
segnare: 1281
brunch: 1282
gelateria: 1283
giapponese: 1284
intrecciare: 1285
lombardo: 1286
nazionalità: 1287
paese: 1288
impalcatura: 1289
piccione: 1290
anatre: 1291
antonomasia: 1292
commistione: 1293
recensire: 1294
suscitare: 1295
ricostruire: 1296
razza: 1297
specialità: 1298
viaggiare: 1299
illuminazione: 1300
immagine: 1301
osservazione: 1302
ristoro: 1303
artigianato: 1304
maggio: 1305
studente: 1306
estendere: 1307
pressi: 1308
conservazione: 1309
convincere: 1310
sconforto: 1311
sconsigliato: 1312
tendere: 1313
errare: 1314
immensa: 1315
televisione: 1316
alimentare: 1317
compere: 1318
mese: 1319
partecipare: 1320
pranzo: 1321
fattura: 1322
meriterebbe: 1323
straordinario: 1324
valorizzare: 1325
secolo: 1326
beneficiare: 1327
distretto: 1328
attaccare: 1329
coco: 1330
cola: 1331
condotto: 1332
inteligente: 1333
passerella: 1334
poltrona: 1335
salutare: 1336
scendere: 1337
uscendo: 1338
voce: 1339
voto: 1340
ambasciata: 1341
fronte: 1342
fumare: 1343
monopattino: 1344
né: 1345
sostare: 1346
fatto: 1347
capitello: 1348
cura: 1349
difetto: 1350
gamba: 1351
impiegare: 1352
settembre: 1353
contrasto: 1354
discutere: 1355
cil: 1356
nascere: 1357
bagno: 1358
pochino: 1359
sbagliare: 1360
passante: 1361
spostare: 1362
gg: 1363
pago: 1364
pioggia: 1365
riconoscere: 1366
successo: 1367
architetto: 1368
costituire: 1369
disorientamento: 1370
europa: 1371
minuto: 1372
pendenza: 1373
richiamare: 1374
riflettere: 1375
succedere: 1376
uccidere: 1377
automobile: 1378
capoluogo: 1379
costruire: 1380
credereste: 1381
toccare: 1382
antico: 1383
antiquariato: 1384
conferma: 1385
design: 1386
genova: 1387
modella: 1388
musicista: 1389
numeroso: 1390
profumare: 1391
top: 1392
zampino: 1393
cattolico: 1394
culto: 1395
patrimonio: 1396
perdervi: 1397
artificio: 1398
assumere: 1399
generano: 1400
aiutare: 1401
invitano: 1402
cartina: 1403
guardandolo: 1404
inerme: 1405
love: 1406
aber: 1407
abito: 1408
arrendere: 1409
gironzolare: 1410
novello: 1411
richiedere: 1412
rifare: 1413
rito: 1414
sopraffatto: 1415
sposo: 1416
life: 1417
rovina: 1418
sottosuolo: 1419
spaziare: 1420
delizia: 1421
sconvolto: 1422
bucato: 1423
collegamento: 1424
ponticello: 1425
portafoglio: 1426
propio: 1427
riva: 1428
maltempo: 1429
avvalsi: 1430
fabbrica: 1431
upper: 1432
scappo: 1433
orecchia: 1434
accontentare: 1435
interessare: 1436
libreria: 1437
prof: 1438
maya: 1439
esibizione: 1440
palco: 1441
zeppo: 1442
baracchino: 1443
the: 1444
avventore: 1445
facente: 1446
intrattenere: 1447
padrone: 1448
ubriaco: 1449
adulto: 1450
carino: 1451
nazismo: 1452
serie: 1453
premettere: 1454
anke: 1455
buffet: 1456
condire: 1457
regina: 1458
box: 1459
gentilezza: 1460
rigore: 1461
sforare: 1462
agosto: 1463
luna: 1464
lunghezza: 1465
tradizione: 1466

In [268]:
dictionary2.filter_extremes(no_below=5,no_above=0.6,keep_n=7500)

In [269]:
X5=[dictionary2.doc2bow(document) for document in complete_corpus]
print("Ecco i primi tre documenti in formato bow (indice,numero di occorrenze)\n ")
print(X5[:3])

Ecco i primi tre documenti in formato bow (indice,numero di occorrenze)

[[(0, 1), (1, 1), (2, 1), (3, 1), (4, 1), (5, 1), (6, 1), (7, 1), (8, 1), (9, 1), (10, 1), (11, 1), (12, 1), (13, 1), (14, 1), (15, 1), (16, 1), (17, 1), (18, 1), (19, 1)], [(20, 1), (21, 1), (22, 1), (23, 1), (24, 1), (25, 1), (26, 1)], [(0, 1), (5, 1), (10, 1), (27, 1), (28, 1), (29, 1), (30, 1), (31, 1), (32, 1), (33, 1), (34, 1), (35, 1), (36, 1), (37, 1), (38, 1), (39, 1), (40, 1), (41, 1)]]

In [270]:
from gensim.models import TfidfModel

In [271]:
_tfidf_=TfidfModel(X5)
X5=_tfidf_[X5]
print("Ecco i primi tre documenti in formato tfidf \n ")
for i in range(3):
    print(X5[i])

Ecco i primi tre documenti in formato tfidf

[(0, np.float64(0.18614788129313536)), (1, np.float64(0.2913459351566503)), (2, np.float64(0.2733231121057014)), (3, np.float64(0.1888652500382927)), (4, np.float64(0.0858416566832036)), (5, np.float64(0.20213304710734392)), (6, np.float64(0.20780152271022043)), (7, np.float64(0.1295415150779732)), (8, np.float64(0.1955967250521033)), (9, np.float64(0.16140458172881184)), (10, np.float64(0.1658774028103028)), (11, np.float64(0.22367636027385476)), (12, np.float64(0.2437300315714356)), (13, np.float64(0.15813430761719843)), (14, np.float64(0.405695576511709)), (15, np.float64(0.28762430033911524)), (16, np.float64(0.3782262929116536)), (17, np.float64(0.1276408441695833)), (18, np.float64(0.08054059845346961)), (19, np.float64(0.1499479821678628))]
[(20, np.float64(0.31276111373316123)), (21, np.float64(0.36497355805113135)), (22, np.float64(0.3382393276244962)), (23, np.float64(0.3420144391585053)), (24, np.float64(0.28913194669365705)), (25, np.float64(0.6564305547947467)), (26, np.float64(0.15197602589918308))]
[(0, np.float64(0.18648702994037106)), (5, np.float64(0.20250131962815834)), (10, np.float64(0.1661796200387734)), (27, np.float64(0.20684620242367202)), (28, np.float64(0.17750664988382384)), (29, np.float64(0.26579572598343537)), (30, np.float64(0.1540271560791609)), (31, np.float64(0.20670011762093443)), (32, np.float64(0.28017529550060993)), (33, np.float64(0.2846737533431671)), (34, np.float64(0.20052468812134527)), (35, np.float64(0.19057373874712832)), (36, np.float64(0.3554532351849551)), (37, np.float64(0.27836244457848136)), (38, np.float64(0.19924820654203634)), (39, np.float64(0.31030886275109687)), (40, np.float64(0.27836244457848136)), (41, np.float64(0.1784206248858003))]

In [272]:
lda_gen=LdaMulticore(X5, num_topics=8, id2word=dictionary2,passes=250 ,workers=4)
#7-8 minuti

In [273]:
for index,topic in lda_gen.print_topics():
    print("\nTOPIC %d - parole più popolari" % (index+1))
    print(topic)

TOPIC 1 - parole più popolari
0.024*"parco" + 0.015*"girare" + 0.015*"bicicletta" + 0.012*"noleggiare" + 0.012*"giro" + 0.009*"bice" + 0.009*"affittare" + 0.008*"park" + 0.007*"central" + 0.007*"film"

TOPIC 2 - parole più popolari
0.009*"assoluto" + 0.007*"stancare" + 0.007*"maya" + 0.006*"illuminato" + 0.006*"settembre" + 0.005*"speciale" + 0.005*"aspettativa" + 0.005*"scontare" + 0.005*"end" + 0.005*"bus"

TOPIC 3 - parole più popolari
0.020*"locale" + 0.017*"zona" + 0.016*"milano" + 0.015*"ristorante" + 0.015*"sera" + 0.011*"bar" + 0.011*"navigli" + 0.010*"aperitivo" + 0.009*"naviglio" + 0.009*"passeggiata"

TOPIC 4 - parole più popolari
0.050*"duomo" + 0.031*"milano" + 0.029*"piazza" + 0.021*"terrazza" + 0.018*"visitare" + 0.017*"simbolo" + 0.016*"salire" + 0.015*"cattedrale" + 0.014*"vista" + 0.013*"guglia"

TOPIC 5 - parole più popolari
0.027*"chiesa" + 0.018*"affresco" + 0.017*"milano" + 0.010*"sistina" + 0.009*"duomo" + 0.009*"visitare" + 0.009*"volontario" + 0.009*"bellezza" + 0.008*"visita" + 0.008*"gioiello"

TOPIC 6 - parole più popolari
0.025*"muro" + 0.022*"berlino" + 0.015*"storia" + 0.010*"porta" + 0.009*"murales" + 0.009*"memoriale" + 0.008*"monumento" + 0.007*"foto" + 0.007*"brandeburgo" + 0.007*"pezzo"

TOPIC 7 - parole più popolari
0.024*"museo" + 0.020*"opera" + 0.015*"visita" + 0.011*"fila" + 0.011*"biglietto" + 0.011*"visitare" + 0.011*"ingresso" + 0.010*"arte" + 0.010*"madrid" + 0.010*"prenotare"

TOPIC 8 - parole più popolari
0.022*"parco" + 0.017*"park" + 0.016*"new" + 0.016*"york" + 0.014*"central" + 0.009*"polmone" + 0.009*"passeggiare" + 0.009*"giornata" + 0.008*"grattacielo" + 0.007*"scoiattolo"

In [274]:
lda_gen_vis=pyLDAvis.gensim.prepare(lda_gen,X5,dictionary2,mds='tsne')
pyLDAvis.display(lda_gen_vis)